namespace OpticaMultivisual.Views.Dashboard.Article
{
    partial class ViewAddArticle
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewAddArticle));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.txtUrlImagenArt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.txtDescArt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtComentariosArt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.btnActualizarArt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAgendarArt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.cmbMaterialArt = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbColorArt = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbTipoArt = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbModeloArt = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtArCodigo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtArNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPUnitario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMedidas = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.tableLayoutPanel1.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.21103F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 67.57271F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.21626F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuPanel1, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.bunifuPictureBox1, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13.96333F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 73.34274F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.69394F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1348, 701);
            this.tableLayoutPanel1.TabIndex = 14;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 30;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel7);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel3);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel6);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel2);
            this.bunifuPanel1.Location = new System.Drawing.Point(221, 99);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(904, 510);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel7.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel7.ColumnCount = 1;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel7.Controls.Add(this.txtUrlImagenArt, 0, 1);
            this.tableLayoutPanel7.Location = new System.Drawing.Point(45, 212);
            this.tableLayoutPanel7.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.RowCount = 4;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.843444F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 76.47359F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.841484F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.841484F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(808, 50);
            this.tableLayoutPanel7.TabIndex = 15;
            // 
            // txtUrlImagenArt
            // 
            this.txtUrlImagenArt.AcceptsReturn = false;
            this.txtUrlImagenArt.AcceptsTab = false;
            this.txtUrlImagenArt.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtUrlImagenArt.AnimationSpeed = 200;
            this.txtUrlImagenArt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrlImagenArt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrlImagenArt.AutoSizeHeight = true;
            this.txtUrlImagenArt.BackColor = System.Drawing.Color.Transparent;
            this.txtUrlImagenArt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrlImagenArt.BackgroundImage")));
            this.txtUrlImagenArt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrlImagenArt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrlImagenArt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrlImagenArt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrlImagenArt.BorderRadius = 15;
            this.txtUrlImagenArt.BorderThickness = 1;
            this.txtUrlImagenArt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUrlImagenArt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrlImagenArt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrlImagenArt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrlImagenArt.DefaultText = "";
            this.txtUrlImagenArt.FillColor = System.Drawing.Color.White;
            this.txtUrlImagenArt.HideSelection = true;
            this.txtUrlImagenArt.IconLeft = null;
            this.txtUrlImagenArt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrlImagenArt.IconPadding = 10;
            this.txtUrlImagenArt.IconRight = null;
            this.txtUrlImagenArt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrlImagenArt.Lines = new string[0];
            this.txtUrlImagenArt.Location = new System.Drawing.Point(3, 5);
            this.txtUrlImagenArt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtUrlImagenArt.MaxLength = 32767;
            this.txtUrlImagenArt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrlImagenArt.Modified = false;
            this.txtUrlImagenArt.Multiline = false;
            this.txtUrlImagenArt.Name = "txtUrlImagenArt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrlImagenArt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrlImagenArt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrlImagenArt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrlImagenArt.OnIdleState = stateProperties4;
            this.txtUrlImagenArt.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtUrlImagenArt.PasswordChar = '\0';
            this.txtUrlImagenArt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUrlImagenArt.PlaceholderText = "URL de la imagen";
            this.txtUrlImagenArt.ReadOnly = false;
            this.txtUrlImagenArt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrlImagenArt.SelectedText = "";
            this.txtUrlImagenArt.SelectionLength = 0;
            this.txtUrlImagenArt.SelectionStart = 0;
            this.txtUrlImagenArt.ShortcutsEnabled = true;
            this.txtUrlImagenArt.Size = new System.Drawing.Size(802, 34);
            this.txtUrlImagenArt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrlImagenArt.TabIndex = 8;
            this.txtUrlImagenArt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrlImagenArt.TextMarginBottom = 0;
            this.txtUrlImagenArt.TextMarginLeft = 3;
            this.txtUrlImagenArt.TextMarginTop = 1;
            this.txtUrlImagenArt.TextPlaceholder = "URL de la imagen";
            this.txtUrlImagenArt.UseSystemPasswordChar = false;
            this.txtUrlImagenArt.WordWrap = true;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel3.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel3.ColumnCount = 3;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1.118012F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 97.8882F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 0.9937888F));
            this.tableLayoutPanel3.Controls.Add(this.txtDescArt, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.txtComentariosArt, 1, 1);
            this.tableLayoutPanel3.Controls.Add(this.tableLayoutPanel5, 1, 3);
            this.tableLayoutPanel3.Location = new System.Drawing.Point(45, 270);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 4;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55.92105F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 44.07895F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 7F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 57F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(804, 215);
            this.tableLayoutPanel3.TabIndex = 7;
            // 
            // txtDescArt
            // 
            this.txtDescArt.AcceptsReturn = false;
            this.txtDescArt.AcceptsTab = false;
            this.txtDescArt.AnimationSpeed = 200;
            this.txtDescArt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDescArt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDescArt.AutoSizeHeight = true;
            this.txtDescArt.BackColor = System.Drawing.Color.Transparent;
            this.txtDescArt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDescArt.BackgroundImage")));
            this.txtDescArt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDescArt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDescArt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDescArt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDescArt.BorderRadius = 15;
            this.txtDescArt.BorderThickness = 1;
            this.txtDescArt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDescArt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDescArt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescArt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDescArt.DefaultText = "";
            this.txtDescArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtDescArt.FillColor = System.Drawing.Color.White;
            this.txtDescArt.HideSelection = true;
            this.txtDescArt.IconLeft = null;
            this.txtDescArt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescArt.IconPadding = 10;
            this.txtDescArt.IconRight = null;
            this.txtDescArt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescArt.Lines = new string[0];
            this.txtDescArt.Location = new System.Drawing.Point(11, 2);
            this.txtDescArt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDescArt.MaxLength = 32767;
            this.txtDescArt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDescArt.Modified = false;
            this.txtDescArt.Multiline = true;
            this.txtDescArt.Name = "txtDescArt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescArt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDescArt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescArt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescArt.OnIdleState = stateProperties8;
            this.txtDescArt.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDescArt.PasswordChar = '\0';
            this.txtDescArt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDescArt.PlaceholderText = "Descripción del producto";
            this.txtDescArt.ReadOnly = false;
            this.txtDescArt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDescArt.SelectedText = "";
            this.txtDescArt.SelectionLength = 0;
            this.txtDescArt.SelectionStart = 0;
            this.txtDescArt.ShortcutsEnabled = true;
            this.txtDescArt.Size = new System.Drawing.Size(781, 80);
            this.txtDescArt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDescArt.TabIndex = 0;
            this.txtDescArt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDescArt.TextMarginBottom = 0;
            this.txtDescArt.TextMarginLeft = 5;
            this.txtDescArt.TextMarginTop = 10;
            this.txtDescArt.TextPlaceholder = "Descripción del producto";
            this.txtDescArt.UseSystemPasswordChar = false;
            this.txtDescArt.WordWrap = true;
            // 
            // txtComentariosArt
            // 
            this.txtComentariosArt.AcceptsReturn = false;
            this.txtComentariosArt.AcceptsTab = false;
            this.txtComentariosArt.AnimationSpeed = 200;
            this.txtComentariosArt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtComentariosArt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtComentariosArt.AutoSizeHeight = true;
            this.txtComentariosArt.BackColor = System.Drawing.Color.Transparent;
            this.txtComentariosArt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtComentariosArt.BackgroundImage")));
            this.txtComentariosArt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtComentariosArt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtComentariosArt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtComentariosArt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtComentariosArt.BorderRadius = 15;
            this.txtComentariosArt.BorderThickness = 1;
            this.txtComentariosArt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtComentariosArt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtComentariosArt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComentariosArt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtComentariosArt.DefaultText = "";
            this.txtComentariosArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtComentariosArt.FillColor = System.Drawing.Color.White;
            this.txtComentariosArt.HideSelection = true;
            this.txtComentariosArt.IconLeft = null;
            this.txtComentariosArt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComentariosArt.IconPadding = 10;
            this.txtComentariosArt.IconRight = null;
            this.txtComentariosArt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComentariosArt.Lines = new string[0];
            this.txtComentariosArt.Location = new System.Drawing.Point(11, 86);
            this.txtComentariosArt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtComentariosArt.MaxLength = 32767;
            this.txtComentariosArt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtComentariosArt.Modified = false;
            this.txtComentariosArt.Multiline = true;
            this.txtComentariosArt.Name = "txtComentariosArt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComentariosArt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtComentariosArt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComentariosArt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComentariosArt.OnIdleState = stateProperties12;
            this.txtComentariosArt.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtComentariosArt.PasswordChar = '\0';
            this.txtComentariosArt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtComentariosArt.PlaceholderText = "Comentarios del producto";
            this.txtComentariosArt.ReadOnly = false;
            this.txtComentariosArt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtComentariosArt.SelectedText = "";
            this.txtComentariosArt.SelectionLength = 0;
            this.txtComentariosArt.SelectionStart = 0;
            this.txtComentariosArt.ShortcutsEnabled = true;
            this.txtComentariosArt.Size = new System.Drawing.Size(781, 62);
            this.txtComentariosArt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtComentariosArt.TabIndex = 8;
            this.txtComentariosArt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtComentariosArt.TextMarginBottom = 0;
            this.txtComentariosArt.TextMarginLeft = 5;
            this.txtComentariosArt.TextMarginTop = 10;
            this.txtComentariosArt.TextPlaceholder = "Comentarios del producto";
            this.txtComentariosArt.UseSystemPasswordChar = false;
            this.txtComentariosArt.WordWrap = true;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel5.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel5.ColumnCount = 3;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 37.34015F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.20205F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.4578F));
            this.tableLayoutPanel5.Controls.Add(this.btnActualizarArt, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnAgendarArt, 2, 0);
            this.tableLayoutPanel5.Location = new System.Drawing.Point(11, 159);
            this.tableLayoutPanel5.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 2;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85.18519F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.81481F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(781, 47);
            this.tableLayoutPanel5.TabIndex = 7;
            // 
            // btnActualizarArt
            // 
            this.btnActualizarArt.AllowAnimations = true;
            this.btnActualizarArt.AllowMouseEffects = true;
            this.btnActualizarArt.AllowToggling = false;
            this.btnActualizarArt.AnimationSpeed = 200;
            this.btnActualizarArt.AutoGenerateColors = false;
            this.btnActualizarArt.AutoRoundBorders = true;
            this.btnActualizarArt.AutoSizeLeftIcon = true;
            this.btnActualizarArt.AutoSizeRightIcon = true;
            this.btnActualizarArt.BackColor = System.Drawing.Color.Transparent;
            this.btnActualizarArt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizarArt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnActualizarArt.BackgroundImage")));
            this.btnActualizarArt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizarArt.ButtonText = "Actualizar";
            this.btnActualizarArt.ButtonTextMarginLeft = 0;
            this.btnActualizarArt.ColorContrastOnClick = 45;
            this.btnActualizarArt.ColorContrastOnHover = 45;
            this.btnActualizarArt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnActualizarArt.CustomizableEdges = borderEdges1;
            this.btnActualizarArt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnActualizarArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizarArt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizarArt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizarArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnActualizarArt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnActualizarArt.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnActualizarArt.ForeColor = System.Drawing.Color.White;
            this.btnActualizarArt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnActualizarArt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizarArt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnActualizarArt.IconMarginLeft = 11;
            this.btnActualizarArt.IconPadding = 10;
            this.btnActualizarArt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnActualizarArt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizarArt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnActualizarArt.IconSize = 25;
            this.btnActualizarArt.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizarArt.IdleBorderRadius = 30;
            this.btnActualizarArt.IdleBorderThickness = 1;
            this.btnActualizarArt.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizarArt.IdleIconLeftImage = null;
            this.btnActualizarArt.IdleIconRightImage = null;
            this.btnActualizarArt.IndicateFocus = false;
            this.btnActualizarArt.Location = new System.Drawing.Point(295, 4);
            this.btnActualizarArt.Margin = new System.Windows.Forms.Padding(4);
            this.btnActualizarArt.Name = "btnActualizarArt";
            this.btnActualizarArt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizarArt.OnDisabledState.BorderRadius = 20;
            this.btnActualizarArt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizarArt.OnDisabledState.BorderThickness = 1;
            this.btnActualizarArt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizarArt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizarArt.OnDisabledState.IconLeftImage = null;
            this.btnActualizarArt.OnDisabledState.IconRightImage = null;
            this.btnActualizarArt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizarArt.onHoverState.BorderRadius = 20;
            this.btnActualizarArt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizarArt.onHoverState.BorderThickness = 1;
            this.btnActualizarArt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizarArt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnActualizarArt.onHoverState.IconLeftImage = null;
            this.btnActualizarArt.onHoverState.IconRightImage = null;
            this.btnActualizarArt.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizarArt.OnIdleState.BorderRadius = 20;
            this.btnActualizarArt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizarArt.OnIdleState.BorderThickness = 1;
            this.btnActualizarArt.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizarArt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnActualizarArt.OnIdleState.IconLeftImage = null;
            this.btnActualizarArt.OnIdleState.IconRightImage = null;
            this.btnActualizarArt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizarArt.OnPressedState.BorderRadius = 20;
            this.btnActualizarArt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizarArt.OnPressedState.BorderThickness = 1;
            this.btnActualizarArt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizarArt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnActualizarArt.OnPressedState.IconLeftImage = null;
            this.btnActualizarArt.OnPressedState.IconRightImage = null;
            this.btnActualizarArt.Size = new System.Drawing.Size(235, 32);
            this.btnActualizarArt.TabIndex = 34;
            this.btnActualizarArt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnActualizarArt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnActualizarArt.TextMarginLeft = 0;
            this.btnActualizarArt.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnActualizarArt.UseDefaultRadiusAndThickness = true;
            // 
            // btnAgendarArt
            // 
            this.btnAgendarArt.AllowAnimations = true;
            this.btnAgendarArt.AllowMouseEffects = true;
            this.btnAgendarArt.AllowToggling = false;
            this.btnAgendarArt.AnimationSpeed = 200;
            this.btnAgendarArt.AutoGenerateColors = false;
            this.btnAgendarArt.AutoRoundBorders = true;
            this.btnAgendarArt.AutoSizeLeftIcon = true;
            this.btnAgendarArt.AutoSizeRightIcon = true;
            this.btnAgendarArt.BackColor = System.Drawing.Color.Transparent;
            this.btnAgendarArt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendarArt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgendarArt.BackgroundImage")));
            this.btnAgendarArt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendarArt.ButtonText = "Agendar";
            this.btnAgendarArt.ButtonTextMarginLeft = 0;
            this.btnAgendarArt.ColorContrastOnClick = 45;
            this.btnAgendarArt.ColorContrastOnHover = 45;
            this.btnAgendarArt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAgendarArt.CustomizableEdges = borderEdges2;
            this.btnAgendarArt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgendarArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendarArt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendarArt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendarArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnAgendarArt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAgendarArt.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgendarArt.ForeColor = System.Drawing.Color.White;
            this.btnAgendarArt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgendarArt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendarArt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgendarArt.IconMarginLeft = 11;
            this.btnAgendarArt.IconPadding = 10;
            this.btnAgendarArt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgendarArt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendarArt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgendarArt.IconSize = 25;
            this.btnAgendarArt.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendarArt.IdleBorderRadius = 30;
            this.btnAgendarArt.IdleBorderThickness = 1;
            this.btnAgendarArt.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendarArt.IdleIconLeftImage = null;
            this.btnAgendarArt.IdleIconRightImage = null;
            this.btnAgendarArt.IndicateFocus = false;
            this.btnAgendarArt.Location = new System.Drawing.Point(538, 4);
            this.btnAgendarArt.Margin = new System.Windows.Forms.Padding(4);
            this.btnAgendarArt.Name = "btnAgendarArt";
            this.btnAgendarArt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendarArt.OnDisabledState.BorderRadius = 20;
            this.btnAgendarArt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendarArt.OnDisabledState.BorderThickness = 1;
            this.btnAgendarArt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendarArt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendarArt.OnDisabledState.IconLeftImage = null;
            this.btnAgendarArt.OnDisabledState.IconRightImage = null;
            this.btnAgendarArt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendarArt.onHoverState.BorderRadius = 20;
            this.btnAgendarArt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendarArt.onHoverState.BorderThickness = 1;
            this.btnAgendarArt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendarArt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgendarArt.onHoverState.IconLeftImage = null;
            this.btnAgendarArt.onHoverState.IconRightImage = null;
            this.btnAgendarArt.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendarArt.OnIdleState.BorderRadius = 20;
            this.btnAgendarArt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendarArt.OnIdleState.BorderThickness = 1;
            this.btnAgendarArt.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendarArt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgendarArt.OnIdleState.IconLeftImage = null;
            this.btnAgendarArt.OnIdleState.IconRightImage = null;
            this.btnAgendarArt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendarArt.OnPressedState.BorderRadius = 20;
            this.btnAgendarArt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendarArt.OnPressedState.BorderThickness = 1;
            this.btnAgendarArt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendarArt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgendarArt.OnPressedState.IconLeftImage = null;
            this.btnAgendarArt.OnPressedState.IconRightImage = null;
            this.btnAgendarArt.Size = new System.Drawing.Size(239, 32);
            this.btnAgendarArt.TabIndex = 35;
            this.btnAgendarArt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgendarArt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgendarArt.TextMarginLeft = 0;
            this.btnAgendarArt.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgendarArt.UseDefaultRadiusAndThickness = true;
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel6.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel6.ColumnCount = 3;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.05445F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34.5297F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel6.Controls.Add(this.label1, 0, 1);
            this.tableLayoutPanel6.Location = new System.Drawing.Point(45, 18);
            this.tableLayoutPanel6.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 3;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15.38461F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 70.76923F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.30769F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(808, 63);
            this.tableLayoutPanel6.TabIndex = 7;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(3, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(253, 45);
            this.label1.TabIndex = 0;
            this.label1.Text = "Artículo";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel2.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel2.ColumnCount = 4;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20.22014F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30.90238F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20.1912F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28.68628F));
            this.tableLayoutPanel2.Controls.Add(this.label5, 3, 1);
            this.tableLayoutPanel2.Controls.Add(this.label4, 2, 1);
            this.tableLayoutPanel2.Controls.Add(this.label3, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.cmbMaterialArt, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.cmbColorArt, 1, 3);
            this.tableLayoutPanel2.Controls.Add(this.cmbTipoArt, 2, 3);
            this.tableLayoutPanel2.Controls.Add(this.cmbModeloArt, 3, 3);
            this.tableLayoutPanel2.Controls.Add(this.txtArCodigo, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.txtArNombre, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.txtPUnitario, 2, 0);
            this.tableLayoutPanel2.Controls.Add(this.txtMedidas, 3, 0);
            this.tableLayoutPanel2.Controls.Add(this.label2, 0, 1);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(45, 87);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 28.78788F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 24.24242F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5.05618F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 41.66667F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(808, 132);
            this.tableLayoutPanel2.TabIndex = 6;
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(578, 45);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 25);
            this.label5.TabIndex = 18;
            this.label5.Text = "Modelo";
            // 
            // label4
            // 
            this.label4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(415, 45);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(50, 25);
            this.label4.TabIndex = 17;
            this.label4.Text = "Tipo";
            // 
            // label3
            // 
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(166, 45);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(57, 25);
            this.label3.TabIndex = 16;
            this.label3.Text = "Color";
            // 
            // cmbMaterialArt
            // 
            this.cmbMaterialArt.BackColor = System.Drawing.Color.Transparent;
            this.cmbMaterialArt.BackgroundColor = System.Drawing.Color.White;
            this.cmbMaterialArt.BorderColor = System.Drawing.Color.Silver;
            this.cmbMaterialArt.BorderRadius = 15;
            this.cmbMaterialArt.Color = System.Drawing.Color.Silver;
            this.cmbMaterialArt.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbMaterialArt.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbMaterialArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbMaterialArt.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbMaterialArt.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbMaterialArt.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbMaterialArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbMaterialArt.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbMaterialArt.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbMaterialArt.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMaterialArt.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbMaterialArt.FillDropDown = true;
            this.cmbMaterialArt.FillIndicator = false;
            this.cmbMaterialArt.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbMaterialArt.Font = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cmbMaterialArt.ForeColor = System.Drawing.Color.Black;
            this.cmbMaterialArt.FormattingEnabled = true;
            this.cmbMaterialArt.Icon = null;
            this.cmbMaterialArt.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbMaterialArt.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbMaterialArt.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbMaterialArt.IndicatorThickness = 2;
            this.cmbMaterialArt.IsDropdownOpened = false;
            this.cmbMaterialArt.ItemBackColor = System.Drawing.Color.White;
            this.cmbMaterialArt.ItemBorderColor = System.Drawing.Color.White;
            this.cmbMaterialArt.ItemForeColor = System.Drawing.Color.Black;
            this.cmbMaterialArt.ItemHeight = 26;
            this.cmbMaterialArt.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbMaterialArt.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbMaterialArt.ItemTopMargin = 3;
            this.cmbMaterialArt.Location = new System.Drawing.Point(3, 78);
            this.cmbMaterialArt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cmbMaterialArt.Name = "cmbMaterialArt";
            this.cmbMaterialArt.Size = new System.Drawing.Size(157, 32);
            this.cmbMaterialArt.TabIndex = 11;
            this.cmbMaterialArt.Text = null;
            this.cmbMaterialArt.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbMaterialArt.TextLeftMargin = 5;
            // 
            // cmbColorArt
            // 
            this.cmbColorArt.BackColor = System.Drawing.Color.Transparent;
            this.cmbColorArt.BackgroundColor = System.Drawing.Color.White;
            this.cmbColorArt.BorderColor = System.Drawing.Color.Silver;
            this.cmbColorArt.BorderRadius = 15;
            this.cmbColorArt.Color = System.Drawing.Color.Silver;
            this.cmbColorArt.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbColorArt.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbColorArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbColorArt.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbColorArt.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbColorArt.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbColorArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbColorArt.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbColorArt.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbColorArt.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbColorArt.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbColorArt.FillDropDown = true;
            this.cmbColorArt.FillIndicator = false;
            this.cmbColorArt.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbColorArt.Font = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cmbColorArt.ForeColor = System.Drawing.Color.Black;
            this.cmbColorArt.FormattingEnabled = true;
            this.cmbColorArt.Icon = null;
            this.cmbColorArt.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbColorArt.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbColorArt.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbColorArt.IndicatorThickness = 2;
            this.cmbColorArt.IsDropdownOpened = false;
            this.cmbColorArt.ItemBackColor = System.Drawing.Color.White;
            this.cmbColorArt.ItemBorderColor = System.Drawing.Color.White;
            this.cmbColorArt.ItemForeColor = System.Drawing.Color.Black;
            this.cmbColorArt.ItemHeight = 26;
            this.cmbColorArt.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbColorArt.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbColorArt.ItemTopMargin = 3;
            this.cmbColorArt.Location = new System.Drawing.Point(183, 78);
            this.cmbColorArt.Margin = new System.Windows.Forms.Padding(20, 2, 20, 2);
            this.cmbColorArt.Name = "cmbColorArt";
            this.cmbColorArt.Size = new System.Drawing.Size(209, 32);
            this.cmbColorArt.TabIndex = 12;
            this.cmbColorArt.Text = null;
            this.cmbColorArt.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbColorArt.TextLeftMargin = 5;
            // 
            // cmbTipoArt
            // 
            this.cmbTipoArt.BackColor = System.Drawing.Color.Transparent;
            this.cmbTipoArt.BackgroundColor = System.Drawing.Color.White;
            this.cmbTipoArt.BorderColor = System.Drawing.Color.Silver;
            this.cmbTipoArt.BorderRadius = 15;
            this.cmbTipoArt.Color = System.Drawing.Color.Silver;
            this.cmbTipoArt.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbTipoArt.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTipoArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbTipoArt.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTipoArt.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbTipoArt.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbTipoArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbTipoArt.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbTipoArt.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbTipoArt.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTipoArt.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTipoArt.FillDropDown = true;
            this.cmbTipoArt.FillIndicator = false;
            this.cmbTipoArt.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTipoArt.Font = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cmbTipoArt.ForeColor = System.Drawing.Color.Black;
            this.cmbTipoArt.FormattingEnabled = true;
            this.cmbTipoArt.Icon = null;
            this.cmbTipoArt.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTipoArt.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbTipoArt.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTipoArt.IndicatorThickness = 2;
            this.cmbTipoArt.IsDropdownOpened = false;
            this.cmbTipoArt.ItemBackColor = System.Drawing.Color.White;
            this.cmbTipoArt.ItemBorderColor = System.Drawing.Color.White;
            this.cmbTipoArt.ItemForeColor = System.Drawing.Color.Black;
            this.cmbTipoArt.ItemHeight = 26;
            this.cmbTipoArt.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbTipoArt.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbTipoArt.ItemTopMargin = 3;
            this.cmbTipoArt.Location = new System.Drawing.Point(415, 78);
            this.cmbTipoArt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cmbTipoArt.Name = "cmbTipoArt";
            this.cmbTipoArt.Size = new System.Drawing.Size(157, 32);
            this.cmbTipoArt.TabIndex = 13;
            this.cmbTipoArt.Text = null;
            this.cmbTipoArt.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTipoArt.TextLeftMargin = 5;
            // 
            // cmbModeloArt
            // 
            this.cmbModeloArt.BackColor = System.Drawing.Color.Transparent;
            this.cmbModeloArt.BackgroundColor = System.Drawing.Color.White;
            this.cmbModeloArt.BorderColor = System.Drawing.Color.Silver;
            this.cmbModeloArt.BorderRadius = 15;
            this.cmbModeloArt.Color = System.Drawing.Color.Silver;
            this.cmbModeloArt.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbModeloArt.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbModeloArt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbModeloArt.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbModeloArt.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbModeloArt.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbModeloArt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbModeloArt.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbModeloArt.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbModeloArt.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbModeloArt.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbModeloArt.FillDropDown = true;
            this.cmbModeloArt.FillIndicator = false;
            this.cmbModeloArt.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbModeloArt.Font = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cmbModeloArt.ForeColor = System.Drawing.Color.Black;
            this.cmbModeloArt.FormattingEnabled = true;
            this.cmbModeloArt.Icon = null;
            this.cmbModeloArt.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbModeloArt.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbModeloArt.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbModeloArt.IndicatorThickness = 2;
            this.cmbModeloArt.IsDropdownOpened = false;
            this.cmbModeloArt.ItemBackColor = System.Drawing.Color.White;
            this.cmbModeloArt.ItemBorderColor = System.Drawing.Color.White;
            this.cmbModeloArt.ItemForeColor = System.Drawing.Color.Black;
            this.cmbModeloArt.ItemHeight = 26;
            this.cmbModeloArt.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbModeloArt.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbModeloArt.ItemTopMargin = 3;
            this.cmbModeloArt.Location = new System.Drawing.Point(615, 78);
            this.cmbModeloArt.Margin = new System.Windows.Forms.Padding(40, 2, 3, 2);
            this.cmbModeloArt.Name = "cmbModeloArt";
            this.cmbModeloArt.Size = new System.Drawing.Size(190, 32);
            this.cmbModeloArt.TabIndex = 14;
            this.cmbModeloArt.Text = null;
            this.cmbModeloArt.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbModeloArt.TextLeftMargin = 5;
            // 
            // txtArCodigo
            // 
            this.txtArCodigo.AcceptsReturn = false;
            this.txtArCodigo.AcceptsTab = false;
            this.txtArCodigo.AnimationSpeed = 200;
            this.txtArCodigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtArCodigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtArCodigo.AutoSizeHeight = true;
            this.txtArCodigo.BackColor = System.Drawing.Color.Transparent;
            this.txtArCodigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtArCodigo.BackgroundImage")));
            this.txtArCodigo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtArCodigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtArCodigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtArCodigo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtArCodigo.BorderRadius = 15;
            this.txtArCodigo.BorderThickness = 1;
            this.txtArCodigo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtArCodigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtArCodigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArCodigo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtArCodigo.DefaultText = "";
            this.txtArCodigo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtArCodigo.FillColor = System.Drawing.Color.White;
            this.txtArCodigo.HideSelection = true;
            this.txtArCodigo.IconLeft = null;
            this.txtArCodigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArCodigo.IconPadding = 10;
            this.txtArCodigo.IconRight = null;
            this.txtArCodigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArCodigo.Lines = new string[0];
            this.txtArCodigo.Location = new System.Drawing.Point(3, 2);
            this.txtArCodigo.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtArCodigo.MaxLength = 32767;
            this.txtArCodigo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtArCodigo.Modified = false;
            this.txtArCodigo.Multiline = false;
            this.txtArCodigo.Name = "txtArCodigo";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArCodigo.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtArCodigo.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArCodigo.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArCodigo.OnIdleState = stateProperties16;
            this.txtArCodigo.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtArCodigo.PasswordChar = '\0';
            this.txtArCodigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtArCodigo.PlaceholderText = "Código";
            this.txtArCodigo.ReadOnly = false;
            this.txtArCodigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtArCodigo.SelectedText = "";
            this.txtArCodigo.SelectionLength = 0;
            this.txtArCodigo.SelectionStart = 0;
            this.txtArCodigo.ShortcutsEnabled = true;
            this.txtArCodigo.Size = new System.Drawing.Size(157, 34);
            this.txtArCodigo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtArCodigo.TabIndex = 7;
            this.txtArCodigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtArCodigo.TextMarginBottom = 0;
            this.txtArCodigo.TextMarginLeft = 3;
            this.txtArCodigo.TextMarginTop = 1;
            this.txtArCodigo.TextPlaceholder = "Código";
            this.txtArCodigo.UseSystemPasswordChar = false;
            this.txtArCodigo.WordWrap = true;
            // 
            // txtArNombre
            // 
            this.txtArNombre.AcceptsReturn = false;
            this.txtArNombre.AcceptsTab = false;
            this.txtArNombre.AnimationSpeed = 200;
            this.txtArNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtArNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtArNombre.AutoSizeHeight = true;
            this.txtArNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtArNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtArNombre.BackgroundImage")));
            this.txtArNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtArNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtArNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtArNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtArNombre.BorderRadius = 15;
            this.txtArNombre.BorderThickness = 1;
            this.txtArNombre.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtArNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtArNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtArNombre.DefaultText = "";
            this.txtArNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtArNombre.FillColor = System.Drawing.Color.White;
            this.txtArNombre.HideSelection = true;
            this.txtArNombre.IconLeft = null;
            this.txtArNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArNombre.IconPadding = 10;
            this.txtArNombre.IconRight = null;
            this.txtArNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtArNombre.Lines = new string[0];
            this.txtArNombre.Location = new System.Drawing.Point(166, 2);
            this.txtArNombre.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtArNombre.MaxLength = 32767;
            this.txtArNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtArNombre.Modified = false;
            this.txtArNombre.Multiline = false;
            this.txtArNombre.Name = "txtArNombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArNombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtArNombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArNombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtArNombre.OnIdleState = stateProperties20;
            this.txtArNombre.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtArNombre.PasswordChar = '\0';
            this.txtArNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtArNombre.PlaceholderText = "Nombre";
            this.txtArNombre.ReadOnly = false;
            this.txtArNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtArNombre.SelectedText = "";
            this.txtArNombre.SelectionLength = 0;
            this.txtArNombre.SelectionStart = 0;
            this.txtArNombre.ShortcutsEnabled = true;
            this.txtArNombre.Size = new System.Drawing.Size(243, 34);
            this.txtArNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtArNombre.TabIndex = 8;
            this.txtArNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtArNombre.TextMarginBottom = 0;
            this.txtArNombre.TextMarginLeft = 3;
            this.txtArNombre.TextMarginTop = 1;
            this.txtArNombre.TextPlaceholder = "Nombre";
            this.txtArNombre.UseSystemPasswordChar = false;
            this.txtArNombre.WordWrap = true;
            // 
            // txtPUnitario
            // 
            this.txtPUnitario.AcceptsReturn = false;
            this.txtPUnitario.AcceptsTab = false;
            this.txtPUnitario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPUnitario.AnimationSpeed = 200;
            this.txtPUnitario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPUnitario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPUnitario.AutoSizeHeight = true;
            this.txtPUnitario.BackColor = System.Drawing.Color.Transparent;
            this.txtPUnitario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPUnitario.BackgroundImage")));
            this.txtPUnitario.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPUnitario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPUnitario.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPUnitario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPUnitario.BorderRadius = 15;
            this.txtPUnitario.BorderThickness = 1;
            this.txtPUnitario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPUnitario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPUnitario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPUnitario.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPUnitario.DefaultText = "";
            this.txtPUnitario.FillColor = System.Drawing.Color.White;
            this.txtPUnitario.HideSelection = true;
            this.txtPUnitario.IconLeft = null;
            this.txtPUnitario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPUnitario.IconPadding = 10;
            this.txtPUnitario.IconRight = null;
            this.txtPUnitario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPUnitario.Lines = new string[0];
            this.txtPUnitario.Location = new System.Drawing.Point(439, 2);
            this.txtPUnitario.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtPUnitario.MaxLength = 32767;
            this.txtPUnitario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPUnitario.Modified = false;
            this.txtPUnitario.Multiline = false;
            this.txtPUnitario.Name = "txtPUnitario";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPUnitario.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPUnitario.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPUnitario.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPUnitario.OnIdleState = stateProperties24;
            this.txtPUnitario.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtPUnitario.PasswordChar = '\0';
            this.txtPUnitario.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPUnitario.PlaceholderText = "Precio Unitario";
            this.txtPUnitario.ReadOnly = false;
            this.txtPUnitario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPUnitario.SelectedText = "";
            this.txtPUnitario.SelectionLength = 0;
            this.txtPUnitario.SelectionStart = 0;
            this.txtPUnitario.ShortcutsEnabled = true;
            this.txtPUnitario.Size = new System.Drawing.Size(133, 32);
            this.txtPUnitario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPUnitario.TabIndex = 9;
            this.txtPUnitario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPUnitario.TextMarginBottom = 0;
            this.txtPUnitario.TextMarginLeft = 3;
            this.txtPUnitario.TextMarginTop = 1;
            this.txtPUnitario.TextPlaceholder = "Precio Unitario";
            this.txtPUnitario.UseSystemPasswordChar = false;
            this.txtPUnitario.WordWrap = true;
            // 
            // txtMedidas
            // 
            this.txtMedidas.AcceptsReturn = false;
            this.txtMedidas.AcceptsTab = false;
            this.txtMedidas.AnimationSpeed = 200;
            this.txtMedidas.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMedidas.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMedidas.AutoSizeHeight = true;
            this.txtMedidas.BackColor = System.Drawing.Color.Transparent;
            this.txtMedidas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMedidas.BackgroundImage")));
            this.txtMedidas.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMedidas.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMedidas.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMedidas.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMedidas.BorderRadius = 15;
            this.txtMedidas.BorderThickness = 1;
            this.txtMedidas.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtMedidas.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMedidas.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMedidas.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMedidas.DefaultText = "";
            this.txtMedidas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtMedidas.FillColor = System.Drawing.Color.White;
            this.txtMedidas.HideSelection = true;
            this.txtMedidas.IconLeft = null;
            this.txtMedidas.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMedidas.IconPadding = 10;
            this.txtMedidas.IconRight = null;
            this.txtMedidas.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMedidas.Lines = new string[0];
            this.txtMedidas.Location = new System.Drawing.Point(595, 2);
            this.txtMedidas.Margin = new System.Windows.Forms.Padding(20, 2, 3, 2);
            this.txtMedidas.MaxLength = 32767;
            this.txtMedidas.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMedidas.Modified = false;
            this.txtMedidas.Multiline = false;
            this.txtMedidas.Name = "txtMedidas";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMedidas.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMedidas.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMedidas.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMedidas.OnIdleState = stateProperties28;
            this.txtMedidas.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtMedidas.PasswordChar = '\0';
            this.txtMedidas.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMedidas.PlaceholderText = "Medidas";
            this.txtMedidas.ReadOnly = false;
            this.txtMedidas.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMedidas.SelectedText = "";
            this.txtMedidas.SelectionLength = 0;
            this.txtMedidas.SelectionStart = 0;
            this.txtMedidas.ShortcutsEnabled = true;
            this.txtMedidas.Size = new System.Drawing.Size(210, 34);
            this.txtMedidas.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMedidas.TabIndex = 10;
            this.txtMedidas.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMedidas.TextMarginBottom = 0;
            this.txtMedidas.TextMarginLeft = 3;
            this.txtMedidas.TextMarginTop = 1;
            this.txtMedidas.TextPlaceholder = "Medidas";
            this.txtMedidas.UseSystemPasswordChar = false;
            this.txtMedidas.WordWrap = true;
            // 
            // label2
            // 
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(3, 45);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(83, 25);
            this.label2.TabIndex = 15;
            this.label2.Text = "Material";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(10, 2);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(197, 93);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // ViewAddArticle
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1348, 701);
            this.Controls.Add(this.tableLayoutPanel1);
            this.MaximumSize = new System.Drawing.Size(1920, 1080);
            this.MinimumSize = new System.Drawing.Size(1366, 748);
            this.Name = "ViewAddArticle";
            this.Text = "ViewAddArticle";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.tableLayoutPanel7.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.tableLayoutPanel6.PerformLayout();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
        public Bunifu.UI.WinForms.BunifuTextBox txtUrlImagenArt;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        public Bunifu.UI.WinForms.BunifuTextBox txtDescArt;
        public Bunifu.UI.WinForms.BunifuTextBox txtComentariosArt;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnActualizarArt;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAgendarArt;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        public Bunifu.UI.WinForms.BunifuDropdown cmbMaterialArt;
        public Bunifu.UI.WinForms.BunifuDropdown cmbColorArt;
        public Bunifu.UI.WinForms.BunifuDropdown cmbTipoArt;
        public Bunifu.UI.WinForms.BunifuDropdown cmbModeloArt;
        public Bunifu.UI.WinForms.BunifuTextBox txtArCodigo;
        public Bunifu.UI.WinForms.BunifuTextBox txtArNombre;
        public Bunifu.UI.WinForms.BunifuTextBox txtPUnitario;
        public Bunifu.UI.WinForms.BunifuTextBox txtMedidas;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}