namespace OpticaMultivisual.Views.Dashboard
{
    partial class ViewMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnVisita = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnClientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnReceta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnConsult = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnArticulo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAdmin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDetalle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnServer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblUsername = new System.Windows.Forms.Label();
            this.btnDoc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.PanelContenedor = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.tableLayoutPanel3.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 21.43917F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 78.56083F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.PanelContenedor, 1, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1350, 709);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.bunifuPictureBox1, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 0, 1);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 2;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 23.62556F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 76.37444F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(283, 703);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::OpticaMultivisual.Properties.Resources.Logo;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(3, 3);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(277, 160);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 6;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.flowLayoutPanel1, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.btnExit, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.tableLayoutPanel4, 0, 2);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 169);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 3;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80.18868F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.622642F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10.18868F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(277, 531);
            this.tableLayoutPanel3.TabIndex = 7;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Controls.Add(this.btnVisita);
            this.flowLayoutPanel1.Controls.Add(this.btnClientes);
            this.flowLayoutPanel1.Controls.Add(this.btnReceta);
            this.flowLayoutPanel1.Controls.Add(this.btnConsult);
            this.flowLayoutPanel1.Controls.Add(this.btnArticulo);
            this.flowLayoutPanel1.Controls.Add(this.btnAdmin);
            this.flowLayoutPanel1.Controls.Add(this.btnDetalle);
            this.flowLayoutPanel1.Controls.Add(this.btnServer);
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(271, 419);
            this.flowLayoutPanel1.TabIndex = 16;
            // 
            // btnVisita
            // 
            this.btnVisita.AllowAnimations = true;
            this.btnVisita.AllowMouseEffects = true;
            this.btnVisita.AllowToggling = false;
            this.btnVisita.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnVisita.AnimationSpeed = 200;
            this.btnVisita.AutoGenerateColors = false;
            this.btnVisita.AutoRoundBorders = false;
            this.btnVisita.AutoSizeLeftIcon = true;
            this.btnVisita.AutoSizeRightIcon = true;
            this.btnVisita.BackColor = System.Drawing.Color.Transparent;
            this.btnVisita.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnVisita.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVisita.BackgroundImage")));
            this.btnVisita.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVisita.ButtonText = "Visita";
            this.btnVisita.ButtonTextMarginLeft = 0;
            this.btnVisita.ColorContrastOnClick = 45;
            this.btnVisita.ColorContrastOnHover = 45;
            this.btnVisita.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnVisita.CustomizableEdges = borderEdges1;
            this.btnVisita.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVisita.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVisita.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVisita.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVisita.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnVisita.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnVisita.ForeColor = System.Drawing.Color.Black;
            this.btnVisita.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVisita.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVisita.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVisita.IconMarginLeft = 11;
            this.btnVisita.IconPadding = 10;
            this.btnVisita.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVisita.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVisita.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVisita.IconSize = 25;
            this.btnVisita.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnVisita.IdleBorderRadius = 20;
            this.btnVisita.IdleBorderThickness = 1;
            this.btnVisita.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnVisita.IdleIconLeftImage = null;
            this.btnVisita.IdleIconRightImage = null;
            this.btnVisita.IndicateFocus = false;
            this.btnVisita.Location = new System.Drawing.Point(20, 10);
            this.btnVisita.Margin = new System.Windows.Forms.Padding(20, 10, 3, 20);
            this.btnVisita.Name = "btnVisita";
            this.btnVisita.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVisita.OnDisabledState.BorderRadius = 20;
            this.btnVisita.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVisita.OnDisabledState.BorderThickness = 1;
            this.btnVisita.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVisita.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVisita.OnDisabledState.IconLeftImage = null;
            this.btnVisita.OnDisabledState.IconRightImage = null;
            this.btnVisita.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVisita.onHoverState.BorderRadius = 20;
            this.btnVisita.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVisita.onHoverState.BorderThickness = 1;
            this.btnVisita.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVisita.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVisita.onHoverState.IconLeftImage = null;
            this.btnVisita.onHoverState.IconRightImage = null;
            this.btnVisita.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnVisita.OnIdleState.BorderRadius = 20;
            this.btnVisita.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVisita.OnIdleState.BorderThickness = 1;
            this.btnVisita.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnVisita.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnVisita.OnIdleState.IconLeftImage = null;
            this.btnVisita.OnIdleState.IconRightImage = null;
            this.btnVisita.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVisita.OnPressedState.BorderRadius = 20;
            this.btnVisita.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVisita.OnPressedState.BorderThickness = 1;
            this.btnVisita.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVisita.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVisita.OnPressedState.IconLeftImage = null;
            this.btnVisita.OnPressedState.IconRightImage = null;
            this.btnVisita.Size = new System.Drawing.Size(228, 28);
            this.btnVisita.TabIndex = 0;
            this.btnVisita.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVisita.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVisita.TextMarginLeft = 0;
            this.btnVisita.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVisita.UseDefaultRadiusAndThickness = true;
            // 
            // btnClientes
            // 
            this.btnClientes.AllowAnimations = true;
            this.btnClientes.AllowMouseEffects = true;
            this.btnClientes.AllowToggling = false;
            this.btnClientes.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnClientes.AnimationSpeed = 200;
            this.btnClientes.AutoGenerateColors = false;
            this.btnClientes.AutoRoundBorders = false;
            this.btnClientes.AutoSizeLeftIcon = true;
            this.btnClientes.AutoSizeRightIcon = true;
            this.btnClientes.BackColor = System.Drawing.Color.Transparent;
            this.btnClientes.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClientes.BackgroundImage")));
            this.btnClientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClientes.ButtonText = "Clientes";
            this.btnClientes.ButtonTextMarginLeft = 0;
            this.btnClientes.ColorContrastOnClick = 45;
            this.btnClientes.ColorContrastOnHover = 45;
            this.btnClientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnClientes.CustomizableEdges = borderEdges2;
            this.btnClientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClientes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClientes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClientes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnClientes.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnClientes.ForeColor = System.Drawing.Color.Black;
            this.btnClientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClientes.IconMarginLeft = 11;
            this.btnClientes.IconPadding = 10;
            this.btnClientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClientes.IconSize = 25;
            this.btnClientes.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnClientes.IdleBorderRadius = 20;
            this.btnClientes.IdleBorderThickness = 1;
            this.btnClientes.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnClientes.IdleIconLeftImage = null;
            this.btnClientes.IdleIconRightImage = null;
            this.btnClientes.IndicateFocus = false;
            this.btnClientes.Location = new System.Drawing.Point(20, 61);
            this.btnClientes.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnClientes.Name = "btnClientes";
            this.btnClientes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClientes.OnDisabledState.BorderRadius = 20;
            this.btnClientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClientes.OnDisabledState.BorderThickness = 1;
            this.btnClientes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClientes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClientes.OnDisabledState.IconLeftImage = null;
            this.btnClientes.OnDisabledState.IconRightImage = null;
            this.btnClientes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClientes.onHoverState.BorderRadius = 20;
            this.btnClientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClientes.onHoverState.BorderThickness = 1;
            this.btnClientes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClientes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClientes.onHoverState.IconLeftImage = null;
            this.btnClientes.onHoverState.IconRightImage = null;
            this.btnClientes.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnClientes.OnIdleState.BorderRadius = 20;
            this.btnClientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClientes.OnIdleState.BorderThickness = 1;
            this.btnClientes.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnClientes.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnClientes.OnIdleState.IconLeftImage = null;
            this.btnClientes.OnIdleState.IconRightImage = null;
            this.btnClientes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClientes.OnPressedState.BorderRadius = 20;
            this.btnClientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClientes.OnPressedState.BorderThickness = 1;
            this.btnClientes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClientes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClientes.OnPressedState.IconLeftImage = null;
            this.btnClientes.OnPressedState.IconRightImage = null;
            this.btnClientes.Size = new System.Drawing.Size(228, 28);
            this.btnClientes.TabIndex = 1;
            this.btnClientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClientes.TextMarginLeft = 0;
            this.btnClientes.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClientes.UseDefaultRadiusAndThickness = true;
            // 
            // btnReceta
            // 
            this.btnReceta.AllowAnimations = true;
            this.btnReceta.AllowMouseEffects = true;
            this.btnReceta.AllowToggling = false;
            this.btnReceta.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnReceta.AnimationSpeed = 200;
            this.btnReceta.AutoGenerateColors = false;
            this.btnReceta.AutoRoundBorders = false;
            this.btnReceta.AutoSizeLeftIcon = true;
            this.btnReceta.AutoSizeRightIcon = true;
            this.btnReceta.BackColor = System.Drawing.Color.Transparent;
            this.btnReceta.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnReceta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReceta.BackgroundImage")));
            this.btnReceta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReceta.ButtonText = "Receta Base";
            this.btnReceta.ButtonTextMarginLeft = 0;
            this.btnReceta.ColorContrastOnClick = 45;
            this.btnReceta.ColorContrastOnHover = 45;
            this.btnReceta.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnReceta.CustomizableEdges = borderEdges3;
            this.btnReceta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReceta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReceta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReceta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReceta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReceta.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnReceta.ForeColor = System.Drawing.Color.Black;
            this.btnReceta.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReceta.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReceta.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReceta.IconMarginLeft = 11;
            this.btnReceta.IconPadding = 10;
            this.btnReceta.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReceta.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReceta.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReceta.IconSize = 25;
            this.btnReceta.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnReceta.IdleBorderRadius = 20;
            this.btnReceta.IdleBorderThickness = 1;
            this.btnReceta.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnReceta.IdleIconLeftImage = null;
            this.btnReceta.IdleIconRightImage = null;
            this.btnReceta.IndicateFocus = false;
            this.btnReceta.Location = new System.Drawing.Point(20, 112);
            this.btnReceta.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnReceta.Name = "btnReceta";
            this.btnReceta.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReceta.OnDisabledState.BorderRadius = 20;
            this.btnReceta.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReceta.OnDisabledState.BorderThickness = 1;
            this.btnReceta.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReceta.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReceta.OnDisabledState.IconLeftImage = null;
            this.btnReceta.OnDisabledState.IconRightImage = null;
            this.btnReceta.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReceta.onHoverState.BorderRadius = 20;
            this.btnReceta.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReceta.onHoverState.BorderThickness = 1;
            this.btnReceta.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReceta.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnReceta.onHoverState.IconLeftImage = null;
            this.btnReceta.onHoverState.IconRightImage = null;
            this.btnReceta.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnReceta.OnIdleState.BorderRadius = 20;
            this.btnReceta.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReceta.OnIdleState.BorderThickness = 1;
            this.btnReceta.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnReceta.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnReceta.OnIdleState.IconLeftImage = null;
            this.btnReceta.OnIdleState.IconRightImage = null;
            this.btnReceta.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReceta.OnPressedState.BorderRadius = 20;
            this.btnReceta.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReceta.OnPressedState.BorderThickness = 1;
            this.btnReceta.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReceta.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReceta.OnPressedState.IconLeftImage = null;
            this.btnReceta.OnPressedState.IconRightImage = null;
            this.btnReceta.Size = new System.Drawing.Size(228, 28);
            this.btnReceta.TabIndex = 2;
            this.btnReceta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReceta.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReceta.TextMarginLeft = 0;
            this.btnReceta.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnReceta.UseDefaultRadiusAndThickness = true;
            // 
            // btnConsult
            // 
            this.btnConsult.AllowAnimations = true;
            this.btnConsult.AllowMouseEffects = true;
            this.btnConsult.AllowToggling = false;
            this.btnConsult.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnConsult.AnimationSpeed = 200;
            this.btnConsult.AutoGenerateColors = false;
            this.btnConsult.AutoRoundBorders = false;
            this.btnConsult.AutoSizeLeftIcon = true;
            this.btnConsult.AutoSizeRightIcon = true;
            this.btnConsult.BackColor = System.Drawing.Color.Transparent;
            this.btnConsult.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnConsult.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConsult.BackgroundImage")));
            this.btnConsult.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsult.ButtonText = "Consulta";
            this.btnConsult.ButtonTextMarginLeft = 0;
            this.btnConsult.ColorContrastOnClick = 45;
            this.btnConsult.ColorContrastOnHover = 45;
            this.btnConsult.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnConsult.CustomizableEdges = borderEdges4;
            this.btnConsult.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConsult.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConsult.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConsult.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConsult.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnConsult.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnConsult.ForeColor = System.Drawing.Color.Black;
            this.btnConsult.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConsult.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConsult.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConsult.IconMarginLeft = 11;
            this.btnConsult.IconPadding = 10;
            this.btnConsult.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConsult.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConsult.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConsult.IconSize = 25;
            this.btnConsult.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnConsult.IdleBorderRadius = 20;
            this.btnConsult.IdleBorderThickness = 1;
            this.btnConsult.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnConsult.IdleIconLeftImage = null;
            this.btnConsult.IdleIconRightImage = null;
            this.btnConsult.IndicateFocus = false;
            this.btnConsult.Location = new System.Drawing.Point(20, 163);
            this.btnConsult.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnConsult.Name = "btnConsult";
            this.btnConsult.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConsult.OnDisabledState.BorderRadius = 20;
            this.btnConsult.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsult.OnDisabledState.BorderThickness = 1;
            this.btnConsult.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConsult.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConsult.OnDisabledState.IconLeftImage = null;
            this.btnConsult.OnDisabledState.IconRightImage = null;
            this.btnConsult.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConsult.onHoverState.BorderRadius = 20;
            this.btnConsult.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsult.onHoverState.BorderThickness = 1;
            this.btnConsult.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConsult.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConsult.onHoverState.IconLeftImage = null;
            this.btnConsult.onHoverState.IconRightImage = null;
            this.btnConsult.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnConsult.OnIdleState.BorderRadius = 20;
            this.btnConsult.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsult.OnIdleState.BorderThickness = 1;
            this.btnConsult.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnConsult.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnConsult.OnIdleState.IconLeftImage = null;
            this.btnConsult.OnIdleState.IconRightImage = null;
            this.btnConsult.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConsult.OnPressedState.BorderRadius = 20;
            this.btnConsult.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsult.OnPressedState.BorderThickness = 1;
            this.btnConsult.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConsult.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConsult.OnPressedState.IconLeftImage = null;
            this.btnConsult.OnPressedState.IconRightImage = null;
            this.btnConsult.Size = new System.Drawing.Size(228, 28);
            this.btnConsult.TabIndex = 3;
            this.btnConsult.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConsult.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConsult.TextMarginLeft = 0;
            this.btnConsult.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnConsult.UseDefaultRadiusAndThickness = true;
            // 
            // btnArticulo
            // 
            this.btnArticulo.AllowAnimations = true;
            this.btnArticulo.AllowMouseEffects = true;
            this.btnArticulo.AllowToggling = false;
            this.btnArticulo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnArticulo.AnimationSpeed = 200;
            this.btnArticulo.AutoGenerateColors = false;
            this.btnArticulo.AutoRoundBorders = false;
            this.btnArticulo.AutoSizeLeftIcon = true;
            this.btnArticulo.AutoSizeRightIcon = true;
            this.btnArticulo.BackColor = System.Drawing.Color.Transparent;
            this.btnArticulo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnArticulo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnArticulo.BackgroundImage")));
            this.btnArticulo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnArticulo.ButtonText = "Articulo";
            this.btnArticulo.ButtonTextMarginLeft = 0;
            this.btnArticulo.ColorContrastOnClick = 45;
            this.btnArticulo.ColorContrastOnHover = 45;
            this.btnArticulo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnArticulo.CustomizableEdges = borderEdges5;
            this.btnArticulo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnArticulo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnArticulo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnArticulo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnArticulo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnArticulo.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnArticulo.ForeColor = System.Drawing.Color.Black;
            this.btnArticulo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnArticulo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnArticulo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnArticulo.IconMarginLeft = 11;
            this.btnArticulo.IconPadding = 10;
            this.btnArticulo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnArticulo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnArticulo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnArticulo.IconSize = 25;
            this.btnArticulo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnArticulo.IdleBorderRadius = 20;
            this.btnArticulo.IdleBorderThickness = 1;
            this.btnArticulo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnArticulo.IdleIconLeftImage = null;
            this.btnArticulo.IdleIconRightImage = null;
            this.btnArticulo.IndicateFocus = false;
            this.btnArticulo.Location = new System.Drawing.Point(20, 214);
            this.btnArticulo.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnArticulo.Name = "btnArticulo";
            this.btnArticulo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnArticulo.OnDisabledState.BorderRadius = 20;
            this.btnArticulo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnArticulo.OnDisabledState.BorderThickness = 1;
            this.btnArticulo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnArticulo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnArticulo.OnDisabledState.IconLeftImage = null;
            this.btnArticulo.OnDisabledState.IconRightImage = null;
            this.btnArticulo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnArticulo.onHoverState.BorderRadius = 20;
            this.btnArticulo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnArticulo.onHoverState.BorderThickness = 1;
            this.btnArticulo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnArticulo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnArticulo.onHoverState.IconLeftImage = null;
            this.btnArticulo.onHoverState.IconRightImage = null;
            this.btnArticulo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnArticulo.OnIdleState.BorderRadius = 20;
            this.btnArticulo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnArticulo.OnIdleState.BorderThickness = 1;
            this.btnArticulo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnArticulo.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnArticulo.OnIdleState.IconLeftImage = null;
            this.btnArticulo.OnIdleState.IconRightImage = null;
            this.btnArticulo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnArticulo.OnPressedState.BorderRadius = 20;
            this.btnArticulo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnArticulo.OnPressedState.BorderThickness = 1;
            this.btnArticulo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnArticulo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnArticulo.OnPressedState.IconLeftImage = null;
            this.btnArticulo.OnPressedState.IconRightImage = null;
            this.btnArticulo.Size = new System.Drawing.Size(228, 28);
            this.btnArticulo.TabIndex = 4;
            this.btnArticulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnArticulo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnArticulo.TextMarginLeft = 0;
            this.btnArticulo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnArticulo.UseDefaultRadiusAndThickness = true;
            // 
            // btnAdmin
            // 
            this.btnAdmin.AllowAnimations = true;
            this.btnAdmin.AllowMouseEffects = true;
            this.btnAdmin.AllowToggling = false;
            this.btnAdmin.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnAdmin.AnimationSpeed = 200;
            this.btnAdmin.AutoGenerateColors = false;
            this.btnAdmin.AutoRoundBorders = false;
            this.btnAdmin.AutoSizeLeftIcon = true;
            this.btnAdmin.AutoSizeRightIcon = true;
            this.btnAdmin.BackColor = System.Drawing.Color.Transparent;
            this.btnAdmin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnAdmin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdmin.BackgroundImage")));
            this.btnAdmin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAdmin.ButtonText = "Administración";
            this.btnAdmin.ButtonTextMarginLeft = 0;
            this.btnAdmin.ColorContrastOnClick = 45;
            this.btnAdmin.ColorContrastOnHover = 45;
            this.btnAdmin.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnAdmin.CustomizableEdges = borderEdges6;
            this.btnAdmin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdmin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdmin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdmin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdmin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAdmin.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnAdmin.ForeColor = System.Drawing.Color.Black;
            this.btnAdmin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdmin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdmin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAdmin.IconMarginLeft = 11;
            this.btnAdmin.IconPadding = 10;
            this.btnAdmin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdmin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdmin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdmin.IconSize = 25;
            this.btnAdmin.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnAdmin.IdleBorderRadius = 20;
            this.btnAdmin.IdleBorderThickness = 1;
            this.btnAdmin.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnAdmin.IdleIconLeftImage = null;
            this.btnAdmin.IdleIconRightImage = null;
            this.btnAdmin.IndicateFocus = false;
            this.btnAdmin.Location = new System.Drawing.Point(20, 265);
            this.btnAdmin.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnAdmin.Name = "btnAdmin";
            this.btnAdmin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdmin.OnDisabledState.BorderRadius = 20;
            this.btnAdmin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAdmin.OnDisabledState.BorderThickness = 1;
            this.btnAdmin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdmin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdmin.OnDisabledState.IconLeftImage = null;
            this.btnAdmin.OnDisabledState.IconRightImage = null;
            this.btnAdmin.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAdmin.onHoverState.BorderRadius = 20;
            this.btnAdmin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAdmin.onHoverState.BorderThickness = 1;
            this.btnAdmin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAdmin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAdmin.onHoverState.IconLeftImage = null;
            this.btnAdmin.onHoverState.IconRightImage = null;
            this.btnAdmin.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnAdmin.OnIdleState.BorderRadius = 20;
            this.btnAdmin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAdmin.OnIdleState.BorderThickness = 1;
            this.btnAdmin.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnAdmin.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnAdmin.OnIdleState.IconLeftImage = null;
            this.btnAdmin.OnIdleState.IconRightImage = null;
            this.btnAdmin.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAdmin.OnPressedState.BorderRadius = 20;
            this.btnAdmin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAdmin.OnPressedState.BorderThickness = 1;
            this.btnAdmin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAdmin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdmin.OnPressedState.IconLeftImage = null;
            this.btnAdmin.OnPressedState.IconRightImage = null;
            this.btnAdmin.Size = new System.Drawing.Size(228, 28);
            this.btnAdmin.TabIndex = 5;
            this.btnAdmin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdmin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdmin.TextMarginLeft = 0;
            this.btnAdmin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAdmin.UseDefaultRadiusAndThickness = true;
            // 
            // btnDetalle
            // 
            this.btnDetalle.AllowAnimations = true;
            this.btnDetalle.AllowMouseEffects = true;
            this.btnDetalle.AllowToggling = false;
            this.btnDetalle.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnDetalle.AnimationSpeed = 200;
            this.btnDetalle.AutoGenerateColors = false;
            this.btnDetalle.AutoRoundBorders = false;
            this.btnDetalle.AutoSizeLeftIcon = true;
            this.btnDetalle.AutoSizeRightIcon = true;
            this.btnDetalle.BackColor = System.Drawing.Color.Transparent;
            this.btnDetalle.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnDetalle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDetalle.BackgroundImage")));
            this.btnDetalle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDetalle.ButtonText = "Pedido Detalle";
            this.btnDetalle.ButtonTextMarginLeft = 0;
            this.btnDetalle.ColorContrastOnClick = 45;
            this.btnDetalle.ColorContrastOnHover = 45;
            this.btnDetalle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnDetalle.CustomizableEdges = borderEdges7;
            this.btnDetalle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDetalle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDetalle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDetalle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDetalle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDetalle.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnDetalle.ForeColor = System.Drawing.Color.Black;
            this.btnDetalle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDetalle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDetalle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDetalle.IconMarginLeft = 11;
            this.btnDetalle.IconPadding = 10;
            this.btnDetalle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDetalle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDetalle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDetalle.IconSize = 25;
            this.btnDetalle.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnDetalle.IdleBorderRadius = 20;
            this.btnDetalle.IdleBorderThickness = 1;
            this.btnDetalle.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnDetalle.IdleIconLeftImage = null;
            this.btnDetalle.IdleIconRightImage = null;
            this.btnDetalle.IndicateFocus = false;
            this.btnDetalle.Location = new System.Drawing.Point(20, 316);
            this.btnDetalle.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnDetalle.Name = "btnDetalle";
            this.btnDetalle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDetalle.OnDisabledState.BorderRadius = 20;
            this.btnDetalle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDetalle.OnDisabledState.BorderThickness = 1;
            this.btnDetalle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDetalle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDetalle.OnDisabledState.IconLeftImage = null;
            this.btnDetalle.OnDisabledState.IconRightImage = null;
            this.btnDetalle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDetalle.onHoverState.BorderRadius = 20;
            this.btnDetalle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDetalle.onHoverState.BorderThickness = 1;
            this.btnDetalle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDetalle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDetalle.onHoverState.IconLeftImage = null;
            this.btnDetalle.onHoverState.IconRightImage = null;
            this.btnDetalle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnDetalle.OnIdleState.BorderRadius = 20;
            this.btnDetalle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDetalle.OnIdleState.BorderThickness = 1;
            this.btnDetalle.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnDetalle.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnDetalle.OnIdleState.IconLeftImage = null;
            this.btnDetalle.OnIdleState.IconRightImage = null;
            this.btnDetalle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDetalle.OnPressedState.BorderRadius = 20;
            this.btnDetalle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDetalle.OnPressedState.BorderThickness = 1;
            this.btnDetalle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDetalle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDetalle.OnPressedState.IconLeftImage = null;
            this.btnDetalle.OnPressedState.IconRightImage = null;
            this.btnDetalle.Size = new System.Drawing.Size(228, 28);
            this.btnDetalle.TabIndex = 6;
            this.btnDetalle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDetalle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDetalle.TextMarginLeft = 0;
            this.btnDetalle.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDetalle.UseDefaultRadiusAndThickness = true;
            // 
            // btnServer
            // 
            this.btnServer.AllowAnimations = true;
            this.btnServer.AllowMouseEffects = true;
            this.btnServer.AllowToggling = false;
            this.btnServer.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnServer.AnimationSpeed = 200;
            this.btnServer.AutoGenerateColors = false;
            this.btnServer.AutoRoundBorders = false;
            this.btnServer.AutoSizeLeftIcon = true;
            this.btnServer.AutoSizeRightIcon = true;
            this.btnServer.BackColor = System.Drawing.Color.Transparent;
            this.btnServer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnServer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnServer.BackgroundImage")));
            this.btnServer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnServer.ButtonText = "Conf. servidor";
            this.btnServer.ButtonTextMarginLeft = 0;
            this.btnServer.ColorContrastOnClick = 45;
            this.btnServer.ColorContrastOnHover = 45;
            this.btnServer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnServer.CustomizableEdges = borderEdges8;
            this.btnServer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnServer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnServer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnServer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnServer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnServer.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnServer.ForeColor = System.Drawing.Color.Black;
            this.btnServer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnServer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnServer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnServer.IconMarginLeft = 11;
            this.btnServer.IconPadding = 10;
            this.btnServer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnServer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnServer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnServer.IconSize = 25;
            this.btnServer.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnServer.IdleBorderRadius = 20;
            this.btnServer.IdleBorderThickness = 1;
            this.btnServer.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnServer.IdleIconLeftImage = null;
            this.btnServer.IdleIconRightImage = null;
            this.btnServer.IndicateFocus = false;
            this.btnServer.Location = new System.Drawing.Point(20, 367);
            this.btnServer.Margin = new System.Windows.Forms.Padding(20, 3, 3, 20);
            this.btnServer.Name = "btnServer";
            this.btnServer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnServer.OnDisabledState.BorderRadius = 20;
            this.btnServer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnServer.OnDisabledState.BorderThickness = 1;
            this.btnServer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnServer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnServer.OnDisabledState.IconLeftImage = null;
            this.btnServer.OnDisabledState.IconRightImage = null;
            this.btnServer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnServer.onHoverState.BorderRadius = 20;
            this.btnServer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnServer.onHoverState.BorderThickness = 1;
            this.btnServer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnServer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnServer.onHoverState.IconLeftImage = null;
            this.btnServer.onHoverState.IconRightImage = null;
            this.btnServer.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnServer.OnIdleState.BorderRadius = 20;
            this.btnServer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnServer.OnIdleState.BorderThickness = 1;
            this.btnServer.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(219)))), ((int)(((byte)(114)))));
            this.btnServer.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnServer.OnIdleState.IconLeftImage = null;
            this.btnServer.OnIdleState.IconRightImage = null;
            this.btnServer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnServer.OnPressedState.BorderRadius = 20;
            this.btnServer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnServer.OnPressedState.BorderThickness = 1;
            this.btnServer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnServer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnServer.OnPressedState.IconLeftImage = null;
            this.btnServer.OnPressedState.IconRightImage = null;
            this.btnServer.Size = new System.Drawing.Size(228, 28);
            this.btnServer.TabIndex = 7;
            this.btnServer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnServer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnServer.TextMarginLeft = 0;
            this.btnServer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnServer.UseDefaultRadiusAndThickness = true;
            // 
            // btnExit
            // 
            this.btnExit.AllowAnimations = true;
            this.btnExit.AllowMouseEffects = true;
            this.btnExit.AllowToggling = false;
            this.btnExit.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnExit.AnimationSpeed = 200;
            this.btnExit.AutoGenerateColors = false;
            this.btnExit.AutoRoundBorders = false;
            this.btnExit.AutoSizeLeftIcon = true;
            this.btnExit.AutoSizeRightIcon = true;
            this.btnExit.BackColor = System.Drawing.Color.Transparent;
            this.btnExit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(178)))), ((int)(((byte)(221)))));
            this.btnExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExit.BackgroundImage")));
            this.btnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnExit.ButtonText = "Cerrar Sesión";
            this.btnExit.ButtonTextMarginLeft = 0;
            this.btnExit.ColorContrastOnClick = 45;
            this.btnExit.ColorContrastOnHover = 45;
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnExit.CustomizableEdges = borderEdges9;
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnExit.Font = new System.Drawing.Font("Segoe UI Semibold", 14F, System.Drawing.FontStyle.Bold);
            this.btnExit.ForeColor = System.Drawing.Color.Black;
            this.btnExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExit.IconMarginLeft = 11;
            this.btnExit.IconPadding = 10;
            this.btnExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExit.IconSize = 25;
            this.btnExit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(178)))), ((int)(((byte)(221)))));
            this.btnExit.IdleBorderRadius = 20;
            this.btnExit.IdleBorderThickness = 1;
            this.btnExit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(178)))), ((int)(((byte)(221)))));
            this.btnExit.IdleIconLeftImage = null;
            this.btnExit.IdleIconRightImage = null;
            this.btnExit.IndicateFocus = false;
            this.btnExit.Location = new System.Drawing.Point(36, 428);
            this.btnExit.Name = "btnExit";
            this.btnExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.OnDisabledState.BorderRadius = 20;
            this.btnExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnExit.OnDisabledState.BorderThickness = 1;
            this.btnExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.OnDisabledState.IconLeftImage = null;
            this.btnExit.OnDisabledState.IconRightImage = null;
            this.btnExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnExit.onHoverState.BorderRadius = 20;
            this.btnExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnExit.onHoverState.BorderThickness = 1;
            this.btnExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnExit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExit.onHoverState.IconLeftImage = null;
            this.btnExit.onHoverState.IconRightImage = null;
            this.btnExit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(178)))), ((int)(((byte)(221)))));
            this.btnExit.OnIdleState.BorderRadius = 20;
            this.btnExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnExit.OnIdleState.BorderThickness = 1;
            this.btnExit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(178)))), ((int)(((byte)(221)))));
            this.btnExit.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnExit.OnIdleState.IconLeftImage = null;
            this.btnExit.OnIdleState.IconRightImage = null;
            this.btnExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExit.OnPressedState.BorderRadius = 20;
            this.btnExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnExit.OnPressedState.BorderThickness = 1;
            this.btnExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnPressedState.IconLeftImage = null;
            this.btnExit.OnPressedState.IconRightImage = null;
            this.btnExit.Size = new System.Drawing.Size(205, 33);
            this.btnExit.TabIndex = 8;
            this.btnExit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExit.TextMarginLeft = 0;
            this.btnExit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExit.UseDefaultRadiusAndThickness = true;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 2;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 81.91882F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18.08118F));
            this.tableLayoutPanel4.Controls.Add(this.bunifuPanel1, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.btnDoc, 1, 0);
            this.tableLayoutPanel4.Location = new System.Drawing.Point(3, 479);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(271, 46);
            this.tableLayoutPanel4.TabIndex = 17;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.bunifuPanel1.BorderRadius = 20;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.lblUsername);
            this.bunifuPanel1.Location = new System.Drawing.Point(13, 3);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(196, 40);
            this.bunifuPanel1.TabIndex = 14;
            // 
            // lblUsername
            // 
            this.lblUsername.AutoSize = true;
            this.lblUsername.BackColor = System.Drawing.Color.Transparent;
            this.lblUsername.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUsername.ForeColor = System.Drawing.Color.White;
            this.lblUsername.Location = new System.Drawing.Point(18, 15);
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.Size = new System.Drawing.Size(11, 15);
            this.lblUsername.TabIndex = 0;
            this.lblUsername.Text = ".";
            // 
            // btnDoc
            // 
            this.btnDoc.AllowAnimations = true;
            this.btnDoc.AllowMouseEffects = true;
            this.btnDoc.AllowToggling = false;
            this.btnDoc.AnimationSpeed = 200;
            this.btnDoc.AutoGenerateColors = false;
            this.btnDoc.AutoRoundBorders = false;
            this.btnDoc.AutoSizeLeftIcon = true;
            this.btnDoc.AutoSizeRightIcon = true;
            this.btnDoc.BackColor = System.Drawing.Color.Transparent;
            this.btnDoc.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnDoc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDoc.BackgroundImage")));
            this.btnDoc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDoc.ButtonText = "";
            this.btnDoc.ButtonTextMarginLeft = 0;
            this.btnDoc.ColorContrastOnClick = 45;
            this.btnDoc.ColorContrastOnHover = 45;
            this.btnDoc.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnDoc.CustomizableEdges = borderEdges10;
            this.btnDoc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDoc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDoc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDoc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDoc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDoc.ForeColor = System.Drawing.Color.White;
            this.btnDoc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDoc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDoc.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDoc.IconMarginLeft = 11;
            this.btnDoc.IconPadding = 10;
            this.btnDoc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDoc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDoc.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDoc.IconSize = 25;
            this.btnDoc.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnDoc.IdleBorderRadius = 20;
            this.btnDoc.IdleBorderThickness = 1;
            this.btnDoc.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnDoc.IdleIconLeftImage = global::OpticaMultivisual.Properties.Resources.Documents;
            this.btnDoc.IdleIconRightImage = null;
            this.btnDoc.IndicateFocus = false;
            this.btnDoc.Location = new System.Drawing.Point(225, 3);
            this.btnDoc.Name = "btnDoc";
            this.btnDoc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDoc.OnDisabledState.BorderRadius = 20;
            this.btnDoc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDoc.OnDisabledState.BorderThickness = 1;
            this.btnDoc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDoc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDoc.OnDisabledState.IconLeftImage = null;
            this.btnDoc.OnDisabledState.IconRightImage = null;
            this.btnDoc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDoc.onHoverState.BorderRadius = 20;
            this.btnDoc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDoc.onHoverState.BorderThickness = 1;
            this.btnDoc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDoc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDoc.onHoverState.IconLeftImage = null;
            this.btnDoc.onHoverState.IconRightImage = null;
            this.btnDoc.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnDoc.OnIdleState.BorderRadius = 20;
            this.btnDoc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDoc.OnIdleState.BorderThickness = 1;
            this.btnDoc.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnDoc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDoc.OnIdleState.IconLeftImage = global::OpticaMultivisual.Properties.Resources.Documents;
            this.btnDoc.OnIdleState.IconRightImage = null;
            this.btnDoc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDoc.OnPressedState.BorderRadius = 20;
            this.btnDoc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDoc.OnPressedState.BorderThickness = 1;
            this.btnDoc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDoc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDoc.OnPressedState.IconLeftImage = null;
            this.btnDoc.OnPressedState.IconRightImage = null;
            this.btnDoc.Size = new System.Drawing.Size(43, 40);
            this.btnDoc.TabIndex = 15;
            this.btnDoc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDoc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDoc.TextMarginLeft = 0;
            this.btnDoc.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDoc.UseDefaultRadiusAndThickness = true;
            // 
            // PanelContenedor
            // 
            this.PanelContenedor.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelContenedor.ColumnCount = 1;
            this.PanelContenedor.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.PanelContenedor.Location = new System.Drawing.Point(292, 3);
            this.PanelContenedor.Name = "PanelContenedor";
            this.PanelContenedor.RowCount = 1;
            this.PanelContenedor.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.PanelContenedor.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 703F));
            this.PanelContenedor.Size = new System.Drawing.Size(1055, 703);
            this.PanelContenedor.TabIndex = 1;
            // 
            // ViewMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(1350, 709);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximumSize = new System.Drawing.Size(1920, 1077);
            this.MinimumSize = new System.Drawing.Size(1027, 591);
            this.Name = "ViewMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Inicio";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.tableLayoutPanel3.ResumeLayout(false);
            this.flowLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        public System.Windows.Forms.TableLayoutPanel PanelContenedor;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnExit;
        public System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnVisita;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClientes;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReceta;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnConsult;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnArticulo;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAdmin;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDetalle;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnServer;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDoc;
    }
}