namespace OpticaMultivisual.Views.ScheduleAppointment
{
    partial class ViewScheduleAppointment
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewScheduleAppointment));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiObs = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel10 = new System.Windows.Forms.TableLayoutPanel();
            this.btnActualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAgendar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.DTPfechacita = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.label2 = new System.Windows.Forms.Label();
            this.tableLayoutPanel8 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiDUI = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiTel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.tableLayoutPanel1.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.tableLayoutPanel10.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel8.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.21103F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 67.57271F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.21626F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuPanel1, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.bunifuPictureBox1, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13.96333F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 73.34274F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.69394F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1028, 609);
            this.tableLayoutPanel1.TabIndex = 13;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 30;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel5);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel10);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel3);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel8);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel6);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel4);
            this.bunifuPanel1.Controls.Add(this.tableLayoutPanel2);
            this.bunifuPanel1.Location = new System.Drawing.Point(168, 87);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(690, 442);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel5.ColumnCount = 1;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.Controls.Add(this.txtCiObs, 0, 0);
            this.tableLayoutPanel5.Location = new System.Drawing.Point(34, 254);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(618, 100);
            this.tableLayoutPanel5.TabIndex = 8;
            // 
            // txtCiObs
            // 
            this.txtCiObs.AcceptsReturn = false;
            this.txtCiObs.AcceptsTab = false;
            this.txtCiObs.AnimationSpeed = 200;
            this.txtCiObs.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiObs.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiObs.AutoSizeHeight = true;
            this.txtCiObs.BackColor = System.Drawing.Color.Transparent;
            this.txtCiObs.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiObs.BackgroundImage")));
            this.txtCiObs.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiObs.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiObs.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiObs.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiObs.BorderRadius = 15;
            this.txtCiObs.BorderThickness = 1;
            this.txtCiObs.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiObs.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiObs.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiObs.DefaultText = "";
            this.txtCiObs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiObs.FillColor = System.Drawing.Color.White;
            this.txtCiObs.HideSelection = true;
            this.txtCiObs.IconLeft = null;
            this.txtCiObs.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.IconPadding = 10;
            this.txtCiObs.IconRight = null;
            this.txtCiObs.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.Lines = new string[0];
            this.txtCiObs.Location = new System.Drawing.Point(3, 3);
            this.txtCiObs.MaxLength = 32767;
            this.txtCiObs.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiObs.Modified = false;
            this.txtCiObs.Multiline = true;
            this.txtCiObs.Name = "txtCiObs";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiObs.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnIdleState = stateProperties4;
            this.txtCiObs.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtCiObs.PasswordChar = '\0';
            this.txtCiObs.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiObs.PlaceholderText = "Observaciones";
            this.txtCiObs.ReadOnly = false;
            this.txtCiObs.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiObs.SelectedText = "";
            this.txtCiObs.SelectionLength = 0;
            this.txtCiObs.SelectionStart = 0;
            this.txtCiObs.ShortcutsEnabled = true;
            this.txtCiObs.Size = new System.Drawing.Size(612, 94);
            this.txtCiObs.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiObs.TabIndex = 0;
            this.txtCiObs.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiObs.TextMarginBottom = 0;
            this.txtCiObs.TextMarginLeft = 5;
            this.txtCiObs.TextMarginTop = 8;
            this.txtCiObs.TextPlaceholder = "Observaciones";
            this.txtCiObs.UseSystemPasswordChar = false;
            this.txtCiObs.WordWrap = true;
            // 
            // tableLayoutPanel10
            // 
            this.tableLayoutPanel10.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel10.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel10.ColumnCount = 3;
            this.tableLayoutPanel10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 37.34015F));
            this.tableLayoutPanel10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.20205F));
            this.tableLayoutPanel10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.4578F));
            this.tableLayoutPanel10.Controls.Add(this.btnActualizar, 1, 0);
            this.tableLayoutPanel10.Controls.Add(this.btnAgendar, 2, 0);
            this.tableLayoutPanel10.Location = new System.Drawing.Point(34, 369);
            this.tableLayoutPanel10.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.tableLayoutPanel10.Name = "tableLayoutPanel10";
            this.tableLayoutPanel10.RowCount = 1;
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85.18519F));
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutPanel10.Size = new System.Drawing.Size(618, 38);
            this.tableLayoutPanel10.TabIndex = 7;
            // 
            // btnActualizar
            // 
            this.btnActualizar.AllowAnimations = true;
            this.btnActualizar.AllowMouseEffects = true;
            this.btnActualizar.AllowToggling = false;
            this.btnActualizar.AnimationSpeed = 200;
            this.btnActualizar.AutoGenerateColors = false;
            this.btnActualizar.AutoRoundBorders = true;
            this.btnActualizar.AutoSizeLeftIcon = true;
            this.btnActualizar.AutoSizeRightIcon = true;
            this.btnActualizar.BackColor = System.Drawing.Color.Transparent;
            this.btnActualizar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnActualizar.BackgroundImage")));
            this.btnActualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.ButtonText = "Actualizar";
            this.btnActualizar.ButtonTextMarginLeft = 0;
            this.btnActualizar.ColorContrastOnClick = 45;
            this.btnActualizar.ColorContrastOnHover = 45;
            this.btnActualizar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnActualizar.CustomizableEdges = borderEdges1;
            this.btnActualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnActualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnActualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnActualizar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnActualizar.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnActualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnActualizar.IconMarginLeft = 11;
            this.btnActualizar.IconPadding = 10;
            this.btnActualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnActualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnActualizar.IconSize = 25;
            this.btnActualizar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.IdleBorderRadius = 30;
            this.btnActualizar.IdleBorderThickness = 1;
            this.btnActualizar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.IdleIconLeftImage = null;
            this.btnActualizar.IdleIconRightImage = null;
            this.btnActualizar.IndicateFocus = false;
            this.btnActualizar.Location = new System.Drawing.Point(233, 3);
            this.btnActualizar.Name = "btnActualizar";
            this.btnActualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.OnDisabledState.BorderRadius = 20;
            this.btnActualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnDisabledState.BorderThickness = 1;
            this.btnActualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.OnDisabledState.IconLeftImage = null;
            this.btnActualizar.OnDisabledState.IconRightImage = null;
            this.btnActualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.BorderRadius = 20;
            this.btnActualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.onHoverState.BorderThickness = 1;
            this.btnActualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.onHoverState.IconLeftImage = null;
            this.btnActualizar.onHoverState.IconRightImage = null;
            this.btnActualizar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.OnIdleState.BorderRadius = 20;
            this.btnActualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnIdleState.BorderThickness = 1;
            this.btnActualizar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnIdleState.IconLeftImage = null;
            this.btnActualizar.OnIdleState.IconRightImage = null;
            this.btnActualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.BorderRadius = 20;
            this.btnActualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnPressedState.BorderThickness = 1;
            this.btnActualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnPressedState.IconLeftImage = null;
            this.btnActualizar.OnPressedState.IconRightImage = null;
            this.btnActualizar.Size = new System.Drawing.Size(186, 32);
            this.btnActualizar.TabIndex = 34;
            this.btnActualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnActualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnActualizar.TextMarginLeft = 0;
            this.btnActualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnActualizar.UseDefaultRadiusAndThickness = true;
            // 
            // btnAgendar
            // 
            this.btnAgendar.AllowAnimations = true;
            this.btnAgendar.AllowMouseEffects = true;
            this.btnAgendar.AllowToggling = false;
            this.btnAgendar.AnimationSpeed = 200;
            this.btnAgendar.AutoGenerateColors = false;
            this.btnAgendar.AutoRoundBorders = true;
            this.btnAgendar.AutoSizeLeftIcon = true;
            this.btnAgendar.AutoSizeRightIcon = true;
            this.btnAgendar.BackColor = System.Drawing.Color.Transparent;
            this.btnAgendar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgendar.BackgroundImage")));
            this.btnAgendar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.ButtonText = "Agendar";
            this.btnAgendar.ButtonTextMarginLeft = 0;
            this.btnAgendar.ColorContrastOnClick = 45;
            this.btnAgendar.ColorContrastOnHover = 45;
            this.btnAgendar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAgendar.CustomizableEdges = borderEdges2;
            this.btnAgendar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgendar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnAgendar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAgendar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgendar.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgendar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgendar.IconMarginLeft = 11;
            this.btnAgendar.IconPadding = 10;
            this.btnAgendar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgendar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgendar.IconSize = 25;
            this.btnAgendar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.IdleBorderRadius = 30;
            this.btnAgendar.IdleBorderThickness = 1;
            this.btnAgendar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.IdleIconLeftImage = null;
            this.btnAgendar.IdleIconRightImage = null;
            this.btnAgendar.IndicateFocus = false;
            this.btnAgendar.Location = new System.Drawing.Point(425, 3);
            this.btnAgendar.Name = "btnAgendar";
            this.btnAgendar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendar.OnDisabledState.BorderRadius = 20;
            this.btnAgendar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnDisabledState.BorderThickness = 1;
            this.btnAgendar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendar.OnDisabledState.IconLeftImage = null;
            this.btnAgendar.OnDisabledState.IconRightImage = null;
            this.btnAgendar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendar.onHoverState.BorderRadius = 20;
            this.btnAgendar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.onHoverState.BorderThickness = 1;
            this.btnAgendar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.onHoverState.IconLeftImage = null;
            this.btnAgendar.onHoverState.IconRightImage = null;
            this.btnAgendar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.OnIdleState.BorderRadius = 20;
            this.btnAgendar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnIdleState.BorderThickness = 1;
            this.btnAgendar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.OnIdleState.IconLeftImage = null;
            this.btnAgendar.OnIdleState.IconRightImage = null;
            this.btnAgendar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendar.OnPressedState.BorderRadius = 20;
            this.btnAgendar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnPressedState.BorderThickness = 1;
            this.btnAgendar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.OnPressedState.IconLeftImage = null;
            this.btnAgendar.OnPressedState.IconRightImage = null;
            this.btnAgendar.Size = new System.Drawing.Size(190, 32);
            this.btnAgendar.TabIndex = 35;
            this.btnAgendar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgendar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgendar.TextMarginLeft = 0;
            this.btnAgendar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgendar.UseDefaultRadiusAndThickness = true;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel3.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel3.ColumnCount = 2;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24.43366F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 75.56635F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel3.Controls.Add(this.DTPfechacita, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.label2, 0, 0);
            this.tableLayoutPanel3.Location = new System.Drawing.Point(34, 198);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(19, 2, 2, 2);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(618, 42);
            this.tableLayoutPanel3.TabIndex = 7;
            // 
            // DTPfechacita
            // 
            this.DTPfechacita.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.DTPfechacita.BackColor = System.Drawing.Color.Transparent;
            this.DTPfechacita.BorderColor = System.Drawing.Color.Silver;
            this.DTPfechacita.BorderRadius = 17;
            this.DTPfechacita.Color = System.Drawing.Color.Silver;
            this.DTPfechacita.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DTPfechacita.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DTPfechacita.DisabledColor = System.Drawing.Color.Gray;
            this.DTPfechacita.DisplayWeekNumbers = false;
            this.DTPfechacita.DPHeight = 0;
            this.DTPfechacita.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DTPfechacita.FillDatePicker = false;
            this.DTPfechacita.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DTPfechacita.ForeColor = System.Drawing.Color.White;
            this.DTPfechacita.Icon = ((System.Drawing.Image)(resources.GetObject("DTPfechacita.Icon")));
            this.DTPfechacita.IconColor = System.Drawing.Color.White;
            this.DTPfechacita.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DTPfechacita.LeftTextMargin = 5;
            this.DTPfechacita.Location = new System.Drawing.Point(153, 2);
            this.DTPfechacita.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.DTPfechacita.MinimumSize = new System.Drawing.Size(4, 32);
            this.DTPfechacita.Name = "DTPfechacita";
            this.DTPfechacita.Size = new System.Drawing.Size(258, 32);
            this.DTPfechacita.TabIndex = 0;
            this.DTPfechacita.Value = new System.DateTime(2024, 9, 1, 11, 29, 0, 0);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(3, 9);
            this.label2.Margin = new System.Windows.Forms.Padding(3, 9, 3, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(140, 21);
            this.label2.TabIndex = 1;
            this.label2.Text = "Fecha de la visita";
            // 
            // tableLayoutPanel8
            // 
            this.tableLayoutPanel8.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel8.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel8.ColumnCount = 3;
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 26.11386F));
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7.054455F));
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 66.70792F));
            this.tableLayoutPanel8.Controls.Add(this.txtCiDUI, 0, 0);
            this.tableLayoutPanel8.Controls.Add(this.txtCiCorreo, 2, 0);
            this.tableLayoutPanel8.Location = new System.Drawing.Point(34, 132);
            this.tableLayoutPanel8.Margin = new System.Windows.Forms.Padding(19, 2, 2, 2);
            this.tableLayoutPanel8.Name = "tableLayoutPanel8";
            this.tableLayoutPanel8.RowCount = 1;
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.tableLayoutPanel8.Size = new System.Drawing.Size(618, 58);
            this.tableLayoutPanel8.TabIndex = 7;
            // 
            // txtCiDUI
            // 
            this.txtCiDUI.AcceptsReturn = false;
            this.txtCiDUI.AcceptsTab = false;
            this.txtCiDUI.AnimationSpeed = 200;
            this.txtCiDUI.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiDUI.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiDUI.AutoSizeHeight = true;
            this.txtCiDUI.BackColor = System.Drawing.Color.Transparent;
            this.txtCiDUI.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiDUI.BackgroundImage")));
            this.txtCiDUI.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiDUI.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiDUI.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiDUI.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiDUI.BorderRadius = 15;
            this.txtCiDUI.BorderThickness = 1;
            this.txtCiDUI.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiDUI.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiDUI.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiDUI.DefaultText = "";
            this.txtCiDUI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiDUI.FillColor = System.Drawing.Color.White;
            this.txtCiDUI.HideSelection = true;
            this.txtCiDUI.IconLeft = null;
            this.txtCiDUI.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.IconPadding = 10;
            this.txtCiDUI.IconRight = null;
            this.txtCiDUI.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.Lines = new string[0];
            this.txtCiDUI.Location = new System.Drawing.Point(2, 11);
            this.txtCiDUI.Margin = new System.Windows.Forms.Padding(2, 11, 2, 10);
            this.txtCiDUI.MaxLength = 32767;
            this.txtCiDUI.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiDUI.Modified = false;
            this.txtCiDUI.Multiline = false;
            this.txtCiDUI.Name = "txtCiDUI";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiDUI.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnIdleState = stateProperties8;
            this.txtCiDUI.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtCiDUI.PasswordChar = '\0';
            this.txtCiDUI.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiDUI.PlaceholderText = "DUI";
            this.txtCiDUI.ReadOnly = false;
            this.txtCiDUI.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiDUI.SelectedText = "";
            this.txtCiDUI.SelectionLength = 0;
            this.txtCiDUI.SelectionStart = 0;
            this.txtCiDUI.ShortcutsEnabled = true;
            this.txtCiDUI.Size = new System.Drawing.Size(157, 37);
            this.txtCiDUI.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiDUI.TabIndex = 7;
            this.txtCiDUI.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiDUI.TextMarginBottom = 0;
            this.txtCiDUI.TextMarginLeft = 3;
            this.txtCiDUI.TextMarginTop = 1;
            this.txtCiDUI.TextPlaceholder = "DUI";
            this.txtCiDUI.UseSystemPasswordChar = false;
            this.txtCiDUI.WordWrap = true;
            // 
            // txtCiCorreo
            // 
            this.txtCiCorreo.AcceptsReturn = false;
            this.txtCiCorreo.AcceptsTab = false;
            this.txtCiCorreo.AnimationSpeed = 200;
            this.txtCiCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiCorreo.AutoSizeHeight = true;
            this.txtCiCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCiCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiCorreo.BackgroundImage")));
            this.txtCiCorreo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiCorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiCorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiCorreo.BorderRadius = 15;
            this.txtCiCorreo.BorderThickness = 1;
            this.txtCiCorreo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiCorreo.DefaultText = "";
            this.txtCiCorreo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiCorreo.FillColor = System.Drawing.Color.White;
            this.txtCiCorreo.HideSelection = true;
            this.txtCiCorreo.IconLeft = null;
            this.txtCiCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.IconPadding = 10;
            this.txtCiCorreo.IconRight = null;
            this.txtCiCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.Lines = new string[0];
            this.txtCiCorreo.Location = new System.Drawing.Point(215, 10);
            this.txtCiCorreo.Margin = new System.Windows.Forms.Padding(11, 10, 2, 11);
            this.txtCiCorreo.MaxLength = 32767;
            this.txtCiCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiCorreo.Modified = false;
            this.txtCiCorreo.Multiline = false;
            this.txtCiCorreo.Name = "txtCiCorreo";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiCorreo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnIdleState = stateProperties12;
            this.txtCiCorreo.Padding = new System.Windows.Forms.Padding(2, 2, 20, 2);
            this.txtCiCorreo.PasswordChar = '\0';
            this.txtCiCorreo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiCorreo.PlaceholderText = "Correo Electrónico";
            this.txtCiCorreo.ReadOnly = false;
            this.txtCiCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiCorreo.SelectedText = "";
            this.txtCiCorreo.SelectionLength = 0;
            this.txtCiCorreo.SelectionStart = 0;
            this.txtCiCorreo.ShortcutsEnabled = true;
            this.txtCiCorreo.Size = new System.Drawing.Size(401, 37);
            this.txtCiCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiCorreo.TabIndex = 10;
            this.txtCiCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiCorreo.TextMarginBottom = 0;
            this.txtCiCorreo.TextMarginLeft = 3;
            this.txtCiCorreo.TextMarginTop = 1;
            this.txtCiCorreo.TextPlaceholder = "Correo Electrónico";
            this.txtCiCorreo.UseSystemPasswordChar = false;
            this.txtCiCorreo.WordWrap = true;
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel6.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel6.ColumnCount = 3;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.05445F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34.5297F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel6.Controls.Add(this.label1, 0, 1);
            this.tableLayoutPanel6.Location = new System.Drawing.Point(34, 15);
            this.tableLayoutPanel6.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 3;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15.38461F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 70.76923F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.30769F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(618, 51);
            this.tableLayoutPanel6.TabIndex = 7;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(2, 7);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(194, 36);
            this.label1.TabIndex = 0;
            this.label1.Text = "Visita";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel4.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel4.ColumnCount = 3;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.93069F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36.01485F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.05445F));
            this.tableLayoutPanel4.Controls.Add(this.txtCiApellido, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.txtCiNombre, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.txtCiTel, 2, 0);
            this.tableLayoutPanel4.Location = new System.Drawing.Point(34, 71);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(19, 2, 2, 2);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(618, 58);
            this.tableLayoutPanel4.TabIndex = 6;
            // 
            // txtCiApellido
            // 
            this.txtCiApellido.AcceptsReturn = false;
            this.txtCiApellido.AcceptsTab = false;
            this.txtCiApellido.AnimationSpeed = 200;
            this.txtCiApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiApellido.AutoSizeHeight = true;
            this.txtCiApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtCiApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiApellido.BackgroundImage")));
            this.txtCiApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiApellido.BorderRadius = 15;
            this.txtCiApellido.BorderThickness = 1;
            this.txtCiApellido.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiApellido.DefaultText = "";
            this.txtCiApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiApellido.FillColor = System.Drawing.Color.White;
            this.txtCiApellido.HideSelection = true;
            this.txtCiApellido.IconLeft = null;
            this.txtCiApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.IconPadding = 10;
            this.txtCiApellido.IconRight = null;
            this.txtCiApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.Lines = new string[0];
            this.txtCiApellido.Location = new System.Drawing.Point(208, 11);
            this.txtCiApellido.Margin = new System.Windows.Forms.Padding(11, 11, 2, 10);
            this.txtCiApellido.MaxLength = 32767;
            this.txtCiApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiApellido.Modified = false;
            this.txtCiApellido.Multiline = false;
            this.txtCiApellido.Name = "txtCiApellido";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiApellido.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnIdleState = stateProperties16;
            this.txtCiApellido.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtCiApellido.PasswordChar = '\0';
            this.txtCiApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiApellido.PlaceholderText = "Apellido";
            this.txtCiApellido.ReadOnly = false;
            this.txtCiApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiApellido.SelectedText = "";
            this.txtCiApellido.SelectionLength = 0;
            this.txtCiApellido.SelectionStart = 0;
            this.txtCiApellido.ShortcutsEnabled = true;
            this.txtCiApellido.Size = new System.Drawing.Size(209, 37);
            this.txtCiApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiApellido.TabIndex = 8;
            this.txtCiApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiApellido.TextMarginBottom = 0;
            this.txtCiApellido.TextMarginLeft = 3;
            this.txtCiApellido.TextMarginTop = 1;
            this.txtCiApellido.TextPlaceholder = "Apellido";
            this.txtCiApellido.UseSystemPasswordChar = false;
            this.txtCiApellido.WordWrap = true;
            // 
            // txtCiNombre
            // 
            this.txtCiNombre.AcceptsReturn = false;
            this.txtCiNombre.AcceptsTab = false;
            this.txtCiNombre.AnimationSpeed = 200;
            this.txtCiNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiNombre.AutoSizeHeight = true;
            this.txtCiNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtCiNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiNombre.BackgroundImage")));
            this.txtCiNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiNombre.BorderRadius = 15;
            this.txtCiNombre.BorderThickness = 1;
            this.txtCiNombre.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiNombre.DefaultText = "";
            this.txtCiNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiNombre.FillColor = System.Drawing.Color.White;
            this.txtCiNombre.HideSelection = true;
            this.txtCiNombre.IconLeft = null;
            this.txtCiNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.IconPadding = 10;
            this.txtCiNombre.IconRight = null;
            this.txtCiNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.Lines = new string[0];
            this.txtCiNombre.Location = new System.Drawing.Point(2, 11);
            this.txtCiNombre.Margin = new System.Windows.Forms.Padding(2, 11, 2, 10);
            this.txtCiNombre.MaxLength = 32767;
            this.txtCiNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiNombre.Modified = false;
            this.txtCiNombre.Multiline = false;
            this.txtCiNombre.Name = "txtCiNombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiNombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnIdleState = stateProperties20;
            this.txtCiNombre.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txtCiNombre.PasswordChar = '\0';
            this.txtCiNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiNombre.PlaceholderText = "Nombre";
            this.txtCiNombre.ReadOnly = false;
            this.txtCiNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiNombre.SelectedText = "";
            this.txtCiNombre.SelectionLength = 0;
            this.txtCiNombre.SelectionStart = 0;
            this.txtCiNombre.ShortcutsEnabled = true;
            this.txtCiNombre.Size = new System.Drawing.Size(193, 37);
            this.txtCiNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiNombre.TabIndex = 7;
            this.txtCiNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiNombre.TextMarginBottom = 0;
            this.txtCiNombre.TextMarginLeft = 3;
            this.txtCiNombre.TextMarginTop = 1;
            this.txtCiNombre.TextPlaceholder = "Nombre";
            this.txtCiNombre.UseSystemPasswordChar = false;
            this.txtCiNombre.WordWrap = true;
            // 
            // txtCiTel
            // 
            this.txtCiTel.AcceptsReturn = false;
            this.txtCiTel.AcceptsTab = false;
            this.txtCiTel.AnimationSpeed = 200;
            this.txtCiTel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiTel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiTel.AutoSizeHeight = true;
            this.txtCiTel.BackColor = System.Drawing.Color.Transparent;
            this.txtCiTel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiTel.BackgroundImage")));
            this.txtCiTel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCiTel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiTel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCiTel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiTel.BorderRadius = 15;
            this.txtCiTel.BorderThickness = 1;
            this.txtCiTel.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiTel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiTel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiTel.DefaultText = "";
            this.txtCiTel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiTel.FillColor = System.Drawing.Color.White;
            this.txtCiTel.HideSelection = true;
            this.txtCiTel.IconLeft = null;
            this.txtCiTel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.IconPadding = 10;
            this.txtCiTel.IconRight = null;
            this.txtCiTel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.Lines = new string[0];
            this.txtCiTel.Location = new System.Drawing.Point(430, 10);
            this.txtCiTel.Margin = new System.Windows.Forms.Padding(11, 10, 2, 11);
            this.txtCiTel.MaxLength = 32767;
            this.txtCiTel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiTel.Modified = false;
            this.txtCiTel.Multiline = false;
            this.txtCiTel.Name = "txtCiTel";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiTel.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnIdleState = stateProperties24;
            this.txtCiTel.Padding = new System.Windows.Forms.Padding(2, 2, 20, 2);
            this.txtCiTel.PasswordChar = '\0';
            this.txtCiTel.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCiTel.PlaceholderText = "Teléfono";
            this.txtCiTel.ReadOnly = false;
            this.txtCiTel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiTel.SelectedText = "";
            this.txtCiTel.SelectionLength = 0;
            this.txtCiTel.SelectionStart = 0;
            this.txtCiTel.ShortcutsEnabled = true;
            this.txtCiTel.Size = new System.Drawing.Size(186, 37);
            this.txtCiTel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiTel.TabIndex = 10;
            this.txtCiTel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiTel.TextMarginBottom = 0;
            this.txtCiTel.TextMarginLeft = 3;
            this.txtCiTel.TextMarginTop = 1;
            this.txtCiTel.TextPlaceholder = "Teléfono";
            this.txtCiTel.UseSystemPasswordChar = false;
            this.txtCiTel.WordWrap = true;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel2.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel2.ColumnCount = 3;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.93069F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36.01485F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.05445F));
            this.tableLayoutPanel2.Controls.Add(this.bunifuTextBox3, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuTextBox2, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuTextBox6, 2, 0);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(34, 71);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(19, 2, 2, 2);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(618, 58);
            this.tableLayoutPanel2.TabIndex = 6;
            // 
            // bunifuTextBox3
            // 
            this.bunifuTextBox3.AcceptsReturn = false;
            this.bunifuTextBox3.AcceptsTab = false;
            this.bunifuTextBox3.AnimationSpeed = 200;
            this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox3.AutoSizeHeight = true;
            this.bunifuTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
            this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox3.BorderRadius = 15;
            this.bunifuTextBox3.BorderThickness = 1;
            this.bunifuTextBox3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox3.DefaultText = "";
            this.bunifuTextBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuTextBox3.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox3.HideSelection = true;
            this.bunifuTextBox3.IconLeft = null;
            this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.IconPadding = 10;
            this.bunifuTextBox3.IconRight = null;
            this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.Lines = new string[0];
            this.bunifuTextBox3.Location = new System.Drawing.Point(208, 11);
            this.bunifuTextBox3.Margin = new System.Windows.Forms.Padding(11, 11, 2, 10);
            this.bunifuTextBox3.MaxLength = 32767;
            this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox3.Modified = false;
            this.bunifuTextBox3.Multiline = false;
            this.bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox3.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnIdleState = stateProperties28;
            this.bunifuTextBox3.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuTextBox3.PasswordChar = '\0';
            this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox3.PlaceholderText = "Apellido";
            this.bunifuTextBox3.ReadOnly = false;
            this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox3.SelectedText = "";
            this.bunifuTextBox3.SelectionLength = 0;
            this.bunifuTextBox3.SelectionStart = 0;
            this.bunifuTextBox3.ShortcutsEnabled = true;
            this.bunifuTextBox3.Size = new System.Drawing.Size(209, 37);
            this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox3.TabIndex = 8;
            this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox3.TextMarginBottom = 0;
            this.bunifuTextBox3.TextMarginLeft = 3;
            this.bunifuTextBox3.TextMarginTop = 1;
            this.bunifuTextBox3.TextPlaceholder = "Apellido";
            this.bunifuTextBox3.UseSystemPasswordChar = false;
            this.bunifuTextBox3.WordWrap = true;
            // 
            // bunifuTextBox2
            // 
            this.bunifuTextBox2.AcceptsReturn = false;
            this.bunifuTextBox2.AcceptsTab = false;
            this.bunifuTextBox2.AnimationSpeed = 200;
            this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox2.AutoSizeHeight = true;
            this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
            this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox2.BorderRadius = 15;
            this.bunifuTextBox2.BorderThickness = 1;
            this.bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox2.DefaultText = "";
            this.bunifuTextBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuTextBox2.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox2.HideSelection = true;
            this.bunifuTextBox2.IconLeft = null;
            this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.IconPadding = 10;
            this.bunifuTextBox2.IconRight = null;
            this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.Lines = new string[0];
            this.bunifuTextBox2.Location = new System.Drawing.Point(2, 11);
            this.bunifuTextBox2.Margin = new System.Windows.Forms.Padding(2, 11, 2, 10);
            this.bunifuTextBox2.MaxLength = 32767;
            this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox2.Modified = false;
            this.bunifuTextBox2.Multiline = false;
            this.bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox2.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnIdleState = stateProperties32;
            this.bunifuTextBox2.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuTextBox2.PasswordChar = '\0';
            this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox2.PlaceholderText = "Nombre";
            this.bunifuTextBox2.ReadOnly = false;
            this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox2.SelectedText = "";
            this.bunifuTextBox2.SelectionLength = 0;
            this.bunifuTextBox2.SelectionStart = 0;
            this.bunifuTextBox2.ShortcutsEnabled = true;
            this.bunifuTextBox2.Size = new System.Drawing.Size(193, 37);
            this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox2.TabIndex = 7;
            this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox2.TextMarginBottom = 0;
            this.bunifuTextBox2.TextMarginLeft = 3;
            this.bunifuTextBox2.TextMarginTop = 1;
            this.bunifuTextBox2.TextPlaceholder = "Nombre";
            this.bunifuTextBox2.UseSystemPasswordChar = false;
            this.bunifuTextBox2.WordWrap = true;
            // 
            // bunifuTextBox6
            // 
            this.bunifuTextBox6.AcceptsReturn = false;
            this.bunifuTextBox6.AcceptsTab = false;
            this.bunifuTextBox6.AnimationSpeed = 200;
            this.bunifuTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox6.AutoSizeHeight = true;
            this.bunifuTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox6.BackgroundImage")));
            this.bunifuTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox6.BorderRadius = 15;
            this.bunifuTextBox6.BorderThickness = 1;
            this.bunifuTextBox6.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox6.DefaultText = "";
            this.bunifuTextBox6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuTextBox6.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox6.HideSelection = true;
            this.bunifuTextBox6.IconLeft = null;
            this.bunifuTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.IconPadding = 10;
            this.bunifuTextBox6.IconRight = null;
            this.bunifuTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.Lines = new string[0];
            this.bunifuTextBox6.Location = new System.Drawing.Point(430, 10);
            this.bunifuTextBox6.Margin = new System.Windows.Forms.Padding(11, 10, 2, 11);
            this.bunifuTextBox6.MaxLength = 32767;
            this.bunifuTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox6.Modified = false;
            this.bunifuTextBox6.Multiline = false;
            this.bunifuTextBox6.Name = "bunifuTextBox6";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox6.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnIdleState = stateProperties36;
            this.bunifuTextBox6.Padding = new System.Windows.Forms.Padding(2, 2, 20, 2);
            this.bunifuTextBox6.PasswordChar = '\0';
            this.bunifuTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox6.PlaceholderText = "Teléfono";
            this.bunifuTextBox6.ReadOnly = false;
            this.bunifuTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox6.SelectedText = "";
            this.bunifuTextBox6.SelectionLength = 0;
            this.bunifuTextBox6.SelectionStart = 0;
            this.bunifuTextBox6.ShortcutsEnabled = true;
            this.bunifuTextBox6.Size = new System.Drawing.Size(186, 37);
            this.bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox6.TabIndex = 10;
            this.bunifuTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox6.TextMarginBottom = 0;
            this.bunifuTextBox6.TextMarginLeft = 3;
            this.bunifuTextBox6.TextMarginTop = 1;
            this.bunifuTextBox6.TextPlaceholder = "Teléfono";
            this.bunifuTextBox6.UseSystemPasswordChar = false;
            this.bunifuTextBox6.WordWrap = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(9, 2);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(148, 81);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // ViewScheduleAppointment
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1028, 609);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "ViewScheduleAppointment";
            this.Text = "ViewScheduleAppointment";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.tableLayoutPanel10.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.tableLayoutPanel8.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.tableLayoutPanel6.PerformLayout();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel10;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnActualizar;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAgendar;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel8;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiDUI;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiCorreo;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiApellido;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiNombre;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiTel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox6;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        public Bunifu.UI.WinForms.BunifuDatePicker DTPfechacita;
        private System.Windows.Forms.Label label2;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiObs;
    }
}