namespace OpticaMultivisual.Views.ScheduleAppointment
{
    partial class ViewScheduleAppointment
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewScheduleAppointment));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel13 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel14 = new System.Windows.Forms.TableLayoutPanel();
            this.label7 = new System.Windows.Forms.Label();
            this.tableLayoutPanel12 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel20 = new System.Windows.Forms.TableLayoutPanel();
            this.btnActualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAgendar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tableLayoutPanel19 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiObs = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel15 = new System.Windows.Forms.TableLayoutPanel();
            this.DTPfechacita = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.tableLayoutPanel17 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiTel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel18 = new System.Windows.Forms.TableLayoutPanel();
            this.txtCiNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiDUI = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCiApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel16 = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.tableLayoutPanel13.SuspendLayout();
            this.tableLayoutPanel14.SuspendLayout();
            this.tableLayoutPanel12.SuspendLayout();
            this.tableLayoutPanel20.SuspendLayout();
            this.tableLayoutPanel19.SuspendLayout();
            this.tableLayoutPanel15.SuspendLayout();
            this.tableLayoutPanel17.SuspendLayout();
            this.tableLayoutPanel18.SuspendLayout();
            this.tableLayoutPanel16.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel13
            // 
            this.tableLayoutPanel13.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.tableLayoutPanel13.ColumnCount = 3;
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.tableLayoutPanel13.Controls.Add(this.tableLayoutPanel14, 1, 1);
            this.tableLayoutPanel13.Controls.Add(this.tableLayoutPanel12, 1, 2);
            this.tableLayoutPanel13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel13.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel13.Margin = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel13.Name = "tableLayoutPanel13";
            this.tableLayoutPanel13.RowCount = 4;
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2.297621F));
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8.890209F));
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 79.79188F));
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.020288F));
            this.tableLayoutPanel13.Size = new System.Drawing.Size(1371, 750);
            this.tableLayoutPanel13.TabIndex = 18;
            // 
            // tableLayoutPanel14
            // 
            this.tableLayoutPanel14.ColumnCount = 5;
            this.tableLayoutPanel14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.061224F));
            this.tableLayoutPanel14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 31.63265F));
            this.tableLayoutPanel14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52.19189F));
            this.tableLayoutPanel14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 6.203474F));
            this.tableLayoutPanel14.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7.526882F));
            this.tableLayoutPanel14.Controls.Add(this.label7, 2, 0);
            this.tableLayoutPanel14.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel14.Location = new System.Drawing.Point(72, 21);
            this.tableLayoutPanel14.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel14.Name = "tableLayoutPanel14";
            this.tableLayoutPanel14.RowCount = 2;
            this.tableLayoutPanel14.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 86.44068F));
            this.tableLayoutPanel14.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13.55932F));
            this.tableLayoutPanel14.Size = new System.Drawing.Size(1225, 58);
            this.tableLayoutPanel14.TabIndex = 13;
            // 
            // label7
            // 
            this.label7.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.label7.Location = new System.Drawing.Point(1053, 14);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(0, 22);
            this.label7.TabIndex = 8;
            // 
            // tableLayoutPanel12
            // 
            this.tableLayoutPanel12.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel12.ColumnCount = 1;
            this.tableLayoutPanel12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel20, 0, 5);
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel19, 0, 4);
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel15, 0, 3);
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel17, 0, 2);
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel18, 0, 1);
            this.tableLayoutPanel12.Controls.Add(this.tableLayoutPanel16, 0, 0);
            this.tableLayoutPanel12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel12.Location = new System.Drawing.Point(72, 87);
            this.tableLayoutPanel12.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel12.Name = "tableLayoutPanel12";
            this.tableLayoutPanel12.RowCount = 6;
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.tableLayoutPanel12.Size = new System.Drawing.Size(1225, 590);
            this.tableLayoutPanel12.TabIndex = 11;
            // 
            // tableLayoutPanel20
            // 
            this.tableLayoutPanel20.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel20.ColumnCount = 4;
            this.tableLayoutPanel20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.912074F));
            this.tableLayoutPanel20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88.41733F));
            this.tableLayoutPanel20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 231F));
            this.tableLayoutPanel20.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 27F));
            this.tableLayoutPanel20.Controls.Add(this.btnActualizar, 1, 0);
            this.tableLayoutPanel20.Controls.Add(this.btnAgendar, 2, 0);
            this.tableLayoutPanel20.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel20.Location = new System.Drawing.Point(4, 538);
            this.tableLayoutPanel20.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel20.Name = "tableLayoutPanel20";
            this.tableLayoutPanel20.RowCount = 1;
            this.tableLayoutPanel20.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel20.Size = new System.Drawing.Size(1217, 48);
            this.tableLayoutPanel20.TabIndex = 20;
            // 
            // btnActualizar
            // 
            this.btnActualizar.AllowAnimations = true;
            this.btnActualizar.AllowMouseEffects = true;
            this.btnActualizar.AllowToggling = false;
            this.btnActualizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnActualizar.AnimationSpeed = 200;
            this.btnActualizar.AutoGenerateColors = false;
            this.btnActualizar.AutoRoundBorders = false;
            this.btnActualizar.AutoSizeLeftIcon = true;
            this.btnActualizar.AutoSizeRightIcon = true;
            this.btnActualizar.BackColor = System.Drawing.Color.Transparent;
            this.btnActualizar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnActualizar.BackgroundImage")));
            this.btnActualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.ButtonText = "Actualizar";
            this.btnActualizar.ButtonTextMarginLeft = 0;
            this.btnActualizar.ColorContrastOnClick = 45;
            this.btnActualizar.ColorContrastOnHover = 45;
            this.btnActualizar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnActualizar.CustomizableEdges = borderEdges1;
            this.btnActualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnActualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnActualizar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnActualizar.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnActualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnActualizar.IconMarginLeft = 11;
            this.btnActualizar.IconPadding = 10;
            this.btnActualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnActualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnActualizar.IconSize = 25;
            this.btnActualizar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.IdleBorderRadius = 20;
            this.btnActualizar.IdleBorderThickness = 1;
            this.btnActualizar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.IdleIconLeftImage = null;
            this.btnActualizar.IdleIconRightImage = null;
            this.btnActualizar.IndicateFocus = false;
            this.btnActualizar.Location = new System.Drawing.Point(762, 4);
            this.btnActualizar.Margin = new System.Windows.Forms.Padding(4);
            this.btnActualizar.Name = "btnActualizar";
            this.btnActualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.OnDisabledState.BorderRadius = 20;
            this.btnActualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnDisabledState.BorderThickness = 1;
            this.btnActualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.OnDisabledState.IconLeftImage = null;
            this.btnActualizar.OnDisabledState.IconRightImage = null;
            this.btnActualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.BorderRadius = 20;
            this.btnActualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.onHoverState.BorderThickness = 1;
            this.btnActualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.onHoverState.IconLeftImage = null;
            this.btnActualizar.onHoverState.IconRightImage = null;
            this.btnActualizar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.OnIdleState.BorderRadius = 20;
            this.btnActualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnIdleState.BorderThickness = 1;
            this.btnActualizar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnActualizar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnIdleState.IconLeftImage = null;
            this.btnActualizar.OnIdleState.IconRightImage = null;
            this.btnActualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.BorderRadius = 20;
            this.btnActualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnPressedState.BorderThickness = 1;
            this.btnActualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnPressedState.IconLeftImage = null;
            this.btnActualizar.OnPressedState.IconRightImage = null;
            this.btnActualizar.Size = new System.Drawing.Size(192, 33);
            this.btnActualizar.TabIndex = 33;
            this.btnActualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnActualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnActualizar.TextMarginLeft = 0;
            this.btnActualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnActualizar.UseDefaultRadiusAndThickness = true;
            // 
            // btnAgendar
            // 
            this.btnAgendar.AllowAnimations = true;
            this.btnAgendar.AllowMouseEffects = true;
            this.btnAgendar.AllowToggling = false;
            this.btnAgendar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAgendar.AnimationSpeed = 200;
            this.btnAgendar.AutoGenerateColors = false;
            this.btnAgendar.AutoRoundBorders = false;
            this.btnAgendar.AutoSizeLeftIcon = true;
            this.btnAgendar.AutoSizeRightIcon = true;
            this.btnAgendar.BackColor = System.Drawing.Color.Transparent;
            this.btnAgendar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgendar.BackgroundImage")));
            this.btnAgendar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.ButtonText = "Agendar";
            this.btnAgendar.ButtonTextMarginLeft = 0;
            this.btnAgendar.ColorContrastOnClick = 45;
            this.btnAgendar.ColorContrastOnHover = 45;
            this.btnAgendar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAgendar.CustomizableEdges = borderEdges2;
            this.btnAgendar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgendar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAgendar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgendar.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgendar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgendar.IconMarginLeft = 11;
            this.btnAgendar.IconPadding = 10;
            this.btnAgendar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgendar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgendar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgendar.IconSize = 25;
            this.btnAgendar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.IdleBorderRadius = 20;
            this.btnAgendar.IdleBorderThickness = 1;
            this.btnAgendar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.IdleIconLeftImage = null;
            this.btnAgendar.IdleIconRightImage = null;
            this.btnAgendar.IndicateFocus = false;
            this.btnAgendar.Location = new System.Drawing.Point(993, 4);
            this.btnAgendar.Margin = new System.Windows.Forms.Padding(4);
            this.btnAgendar.Name = "btnAgendar";
            this.btnAgendar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgendar.OnDisabledState.BorderRadius = 20;
            this.btnAgendar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnDisabledState.BorderThickness = 1;
            this.btnAgendar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgendar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgendar.OnDisabledState.IconLeftImage = null;
            this.btnAgendar.OnDisabledState.IconRightImage = null;
            this.btnAgendar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendar.onHoverState.BorderRadius = 20;
            this.btnAgendar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.onHoverState.BorderThickness = 1;
            this.btnAgendar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgendar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.onHoverState.IconLeftImage = null;
            this.btnAgendar.onHoverState.IconRightImage = null;
            this.btnAgendar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.OnIdleState.BorderRadius = 20;
            this.btnAgendar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnIdleState.BorderThickness = 1;
            this.btnAgendar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(31)))), ((int)(((byte)(92)))));
            this.btnAgendar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.OnIdleState.IconLeftImage = null;
            this.btnAgendar.OnIdleState.IconRightImage = null;
            this.btnAgendar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendar.OnPressedState.BorderRadius = 20;
            this.btnAgendar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgendar.OnPressedState.BorderThickness = 1;
            this.btnAgendar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgendar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgendar.OnPressedState.IconLeftImage = null;
            this.btnAgendar.OnPressedState.IconRightImage = null;
            this.btnAgendar.Size = new System.Drawing.Size(192, 33);
            this.btnAgendar.TabIndex = 34;
            this.btnAgendar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgendar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgendar.TextMarginLeft = 0;
            this.btnAgendar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgendar.UseDefaultRadiusAndThickness = true;
            // 
            // tableLayoutPanel19
            // 
            this.tableLayoutPanel19.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel19.ColumnCount = 3;
            this.tableLayoutPanel19.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.905893F));
            this.tableLayoutPanel19.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88.30608F));
            this.tableLayoutPanel19.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 6.788029F));
            this.tableLayoutPanel19.Controls.Add(this.txtCiObs, 1, 0);
            this.tableLayoutPanel19.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel19.Location = new System.Drawing.Point(4, 302);
            this.tableLayoutPanel19.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel19.Name = "tableLayoutPanel19";
            this.tableLayoutPanel19.RowCount = 1;
            this.tableLayoutPanel19.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel19.Size = new System.Drawing.Size(1217, 228);
            this.tableLayoutPanel19.TabIndex = 18;
            // 
            // txtCiObs
            // 
            this.txtCiObs.AcceptsReturn = false;
            this.txtCiObs.AcceptsTab = false;
            this.txtCiObs.AnimationSpeed = 200;
            this.txtCiObs.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiObs.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiObs.AutoSizeHeight = true;
            this.txtCiObs.BackColor = System.Drawing.Color.Transparent;
            this.txtCiObs.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiObs.BackgroundImage")));
            this.txtCiObs.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiObs.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiObs.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiObs.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiObs.BorderRadius = 20;
            this.txtCiObs.BorderThickness = 1;
            this.txtCiObs.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiObs.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiObs.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCiObs.DefaultText = "";
            this.txtCiObs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiObs.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiObs.HideSelection = true;
            this.txtCiObs.IconLeft = null;
            this.txtCiObs.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.IconPadding = 10;
            this.txtCiObs.IconRight = null;
            this.txtCiObs.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiObs.Lines = new string[0];
            this.txtCiObs.Location = new System.Drawing.Point(63, 4);
            this.txtCiObs.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiObs.MaxLength = 32767;
            this.txtCiObs.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiObs.Modified = false;
            this.txtCiObs.Multiline = true;
            this.txtCiObs.Name = "txtCiObs";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiObs.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiObs.OnIdleState = stateProperties4;
            this.txtCiObs.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiObs.PasswordChar = '\0';
            this.txtCiObs.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiObs.PlaceholderText = "Motivo de la visita";
            this.txtCiObs.ReadOnly = false;
            this.txtCiObs.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiObs.SelectedText = "";
            this.txtCiObs.SelectionLength = 0;
            this.txtCiObs.SelectionStart = 0;
            this.txtCiObs.ShortcutsEnabled = true;
            this.txtCiObs.Size = new System.Drawing.Size(1066, 220);
            this.txtCiObs.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiObs.TabIndex = 29;
            this.txtCiObs.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiObs.TextMarginBottom = 0;
            this.txtCiObs.TextMarginLeft = 1;
            this.txtCiObs.TextMarginTop = 1;
            this.txtCiObs.TextPlaceholder = "Motivo de la visita";
            this.txtCiObs.UseSystemPasswordChar = false;
            this.txtCiObs.WordWrap = true;
            // 
            // tableLayoutPanel15
            // 
            this.tableLayoutPanel15.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel15.ColumnCount = 3;
            this.tableLayoutPanel15.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.093037F));
            this.tableLayoutPanel15.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88.21804F));
            this.tableLayoutPanel15.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 6.688922F));
            this.tableLayoutPanel15.Controls.Add(this.DTPfechacita, 1, 0);
            this.tableLayoutPanel15.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel15.Location = new System.Drawing.Point(4, 238);
            this.tableLayoutPanel15.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel15.Name = "tableLayoutPanel15";
            this.tableLayoutPanel15.RowCount = 2;
            this.tableLayoutPanel15.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 82.6087F));
            this.tableLayoutPanel15.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 17.3913F));
            this.tableLayoutPanel15.Size = new System.Drawing.Size(1217, 56);
            this.tableLayoutPanel15.TabIndex = 19;
            // 
            // DTPfechacita
            // 
            this.DTPfechacita.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.DTPfechacita.BorderColor = System.Drawing.Color.Silver;
            this.DTPfechacita.BorderRadius = 17;
            this.DTPfechacita.Color = System.Drawing.Color.Silver;
            this.DTPfechacita.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DTPfechacita.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DTPfechacita.DisabledColor = System.Drawing.Color.Gray;
            this.DTPfechacita.DisplayWeekNumbers = false;
            this.DTPfechacita.DPHeight = 0;
            this.DTPfechacita.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DTPfechacita.FillDatePicker = false;
            this.DTPfechacita.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DTPfechacita.ForeColor = System.Drawing.Color.DimGray;
            this.DTPfechacita.Icon = ((System.Drawing.Image)(resources.GetObject("DTPfechacita.Icon")));
            this.DTPfechacita.IconColor = System.Drawing.Color.DimGray;
            this.DTPfechacita.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DTPfechacita.LeftTextMargin = 5;
            this.DTPfechacita.Location = new System.Drawing.Point(65, 4);
            this.DTPfechacita.Margin = new System.Windows.Forms.Padding(4);
            this.DTPfechacita.MinimumSize = new System.Drawing.Size(4, 32);
            this.DTPfechacita.Name = "DTPfechacita";
            this.DTPfechacita.Size = new System.Drawing.Size(481, 34);
            this.DTPfechacita.TabIndex = 1;
            // 
            // tableLayoutPanel17
            // 
            this.tableLayoutPanel17.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel17.ColumnCount = 7;
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.137294F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25.18527F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.217219F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35.41147F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 0.6650041F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 23.94015F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 6.264993F));
            this.tableLayoutPanel17.Controls.Add(this.txtCiTel, 1, 0);
            this.tableLayoutPanel17.Controls.Add(this.txtCiCorreo, 3, 0);
            this.tableLayoutPanel17.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel17.Location = new System.Drawing.Point(4, 174);
            this.tableLayoutPanel17.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel17.Name = "tableLayoutPanel17";
            this.tableLayoutPanel17.RowCount = 2;
            this.tableLayoutPanel17.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 66.66666F));
            this.tableLayoutPanel17.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel17.Size = new System.Drawing.Size(1217, 56);
            this.tableLayoutPanel17.TabIndex = 15;
            // 
            // txtCiTel
            // 
            this.txtCiTel.AcceptsReturn = false;
            this.txtCiTel.AcceptsTab = false;
            this.txtCiTel.AnimationSpeed = 200;
            this.txtCiTel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiTel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiTel.AutoSizeHeight = true;
            this.txtCiTel.BackColor = System.Drawing.Color.Transparent;
            this.txtCiTel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiTel.BackgroundImage")));
            this.txtCiTel.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiTel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiTel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiTel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiTel.BorderRadius = 20;
            this.txtCiTel.BorderThickness = 1;
            this.txtCiTel.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiTel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiTel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiTel.DefaultText = "";
            this.txtCiTel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiTel.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiTel.HideSelection = true;
            this.txtCiTel.IconLeft = null;
            this.txtCiTel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.IconPadding = 10;
            this.txtCiTel.IconRight = null;
            this.txtCiTel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiTel.Lines = new string[0];
            this.txtCiTel.Location = new System.Drawing.Point(66, 4);
            this.txtCiTel.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiTel.MaxLength = 32767;
            this.txtCiTel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiTel.Modified = false;
            this.txtCiTel.Multiline = false;
            this.txtCiTel.Name = "txtCiTel";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiTel.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiTel.OnIdleState = stateProperties8;
            this.txtCiTel.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiTel.PasswordChar = '\0';
            this.txtCiTel.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiTel.PlaceholderText = "Teléfono";
            this.txtCiTel.ReadOnly = false;
            this.txtCiTel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiTel.SelectedText = "";
            this.txtCiTel.SelectionLength = 0;
            this.txtCiTel.SelectionStart = 0;
            this.txtCiTel.ShortcutsEnabled = true;
            this.txtCiTel.Size = new System.Drawing.Size(299, 29);
            this.txtCiTel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiTel.TabIndex = 29;
            this.txtCiTel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiTel.TextMarginBottom = 0;
            this.txtCiTel.TextMarginLeft = 1;
            this.txtCiTel.TextMarginTop = 1;
            this.txtCiTel.TextPlaceholder = "Teléfono";
            this.txtCiTel.UseSystemPasswordChar = false;
            this.txtCiTel.WordWrap = true;
            // 
            // txtCiCorreo
            // 
            this.txtCiCorreo.AcceptsReturn = false;
            this.txtCiCorreo.AcceptsTab = false;
            this.txtCiCorreo.AnimationSpeed = 200;
            this.txtCiCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiCorreo.AutoSizeHeight = true;
            this.txtCiCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCiCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiCorreo.BackgroundImage")));
            this.txtCiCorreo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiCorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiCorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiCorreo.BorderRadius = 20;
            this.txtCiCorreo.BorderThickness = 1;
            this.txtCiCorreo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiCorreo.DefaultText = "";
            this.txtCiCorreo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiCorreo.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiCorreo.HideSelection = true;
            this.txtCiCorreo.IconLeft = null;
            this.txtCiCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.IconPadding = 10;
            this.txtCiCorreo.IconRight = null;
            this.txtCiCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiCorreo.Lines = new string[0];
            this.txtCiCorreo.Location = new System.Drawing.Point(412, 4);
            this.txtCiCorreo.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiCorreo.MaxLength = 32767;
            this.txtCiCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiCorreo.Modified = false;
            this.txtCiCorreo.Multiline = false;
            this.txtCiCorreo.Name = "txtCiCorreo";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiCorreo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiCorreo.OnIdleState = stateProperties12;
            this.txtCiCorreo.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiCorreo.PasswordChar = '\0';
            this.txtCiCorreo.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiCorreo.PlaceholderText = "Correo";
            this.txtCiCorreo.ReadOnly = false;
            this.txtCiCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiCorreo.SelectedText = "";
            this.txtCiCorreo.SelectionLength = 0;
            this.txtCiCorreo.SelectionStart = 0;
            this.txtCiCorreo.ShortcutsEnabled = true;
            this.txtCiCorreo.Size = new System.Drawing.Size(423, 29);
            this.txtCiCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiCorreo.TabIndex = 30;
            this.txtCiCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiCorreo.TextMarginBottom = 0;
            this.txtCiCorreo.TextMarginLeft = 1;
            this.txtCiCorreo.TextMarginTop = 1;
            this.txtCiCorreo.TextPlaceholder = "Correo";
            this.txtCiCorreo.UseSystemPasswordChar = false;
            this.txtCiCorreo.WordWrap = true;
            // 
            // tableLayoutPanel18
            // 
            this.tableLayoutPanel18.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel18.ColumnCount = 7;
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.061473F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 17.7437F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.381161F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.092F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 0.6650041F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34.61117F));
            this.tableLayoutPanel18.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.289672F));
            this.tableLayoutPanel18.Controls.Add(this.txtCiNombre, 3, 0);
            this.tableLayoutPanel18.Controls.Add(this.txtCiDUI, 1, 0);
            this.tableLayoutPanel18.Controls.Add(this.txtCiApellido, 5, 0);
            this.tableLayoutPanel18.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel18.Location = new System.Drawing.Point(4, 110);
            this.tableLayoutPanel18.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel18.Name = "tableLayoutPanel18";
            this.tableLayoutPanel18.RowCount = 2;
            this.tableLayoutPanel18.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 66.66666F));
            this.tableLayoutPanel18.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel18.Size = new System.Drawing.Size(1217, 56);
            this.tableLayoutPanel18.TabIndex = 16;
            // 
            // txtCiNombre
            // 
            this.txtCiNombre.AcceptsReturn = false;
            this.txtCiNombre.AcceptsTab = false;
            this.txtCiNombre.AnimationSpeed = 200;
            this.txtCiNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiNombre.AutoSizeHeight = true;
            this.txtCiNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtCiNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiNombre.BackgroundImage")));
            this.txtCiNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiNombre.BorderRadius = 20;
            this.txtCiNombre.BorderThickness = 1;
            this.txtCiNombre.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiNombre.DefaultText = "";
            this.txtCiNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiNombre.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiNombre.HideSelection = true;
            this.txtCiNombre.IconLeft = null;
            this.txtCiNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.IconPadding = 10;
            this.txtCiNombre.IconRight = null;
            this.txtCiNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiNombre.Lines = new string[0];
            this.txtCiNombre.Location = new System.Drawing.Point(334, 4);
            this.txtCiNombre.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiNombre.MaxLength = 32767;
            this.txtCiNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiNombre.Modified = false;
            this.txtCiNombre.Multiline = false;
            this.txtCiNombre.Name = "txtCiNombre";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiNombre.OnIdleState = stateProperties16;
            this.txtCiNombre.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiNombre.PasswordChar = '\0';
            this.txtCiNombre.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiNombre.PlaceholderText = "Nombre";
            this.txtCiNombre.ReadOnly = false;
            this.txtCiNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiNombre.SelectedText = "";
            this.txtCiNombre.SelectionLength = 0;
            this.txtCiNombre.SelectionStart = 0;
            this.txtCiNombre.ShortcutsEnabled = true;
            this.txtCiNombre.Size = new System.Drawing.Size(383, 29);
            this.txtCiNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiNombre.TabIndex = 27;
            this.txtCiNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiNombre.TextMarginBottom = 0;
            this.txtCiNombre.TextMarginLeft = 1;
            this.txtCiNombre.TextMarginTop = 1;
            this.txtCiNombre.TextPlaceholder = "Nombre";
            this.txtCiNombre.UseSystemPasswordChar = false;
            this.txtCiNombre.WordWrap = true;
            // 
            // txtCiDUI
            // 
            this.txtCiDUI.AcceptsReturn = false;
            this.txtCiDUI.AcceptsTab = false;
            this.txtCiDUI.AnimationSpeed = 200;
            this.txtCiDUI.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiDUI.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiDUI.AutoSizeHeight = true;
            this.txtCiDUI.BackColor = System.Drawing.Color.Transparent;
            this.txtCiDUI.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiDUI.BackgroundImage")));
            this.txtCiDUI.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiDUI.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiDUI.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiDUI.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiDUI.BorderRadius = 20;
            this.txtCiDUI.BorderThickness = 1;
            this.txtCiDUI.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiDUI.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiDUI.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiDUI.DefaultText = "";
            this.txtCiDUI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiDUI.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiDUI.HideSelection = true;
            this.txtCiDUI.IconLeft = null;
            this.txtCiDUI.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.IconPadding = 10;
            this.txtCiDUI.IconRight = null;
            this.txtCiDUI.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiDUI.Lines = new string[0];
            this.txtCiDUI.Location = new System.Drawing.Point(65, 4);
            this.txtCiDUI.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiDUI.MaxLength = 32767;
            this.txtCiDUI.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiDUI.Modified = false;
            this.txtCiDUI.Multiline = false;
            this.txtCiDUI.Name = "txtCiDUI";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiDUI.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiDUI.OnIdleState = stateProperties20;
            this.txtCiDUI.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiDUI.PasswordChar = '\0';
            this.txtCiDUI.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiDUI.PlaceholderText = "DUI";
            this.txtCiDUI.ReadOnly = false;
            this.txtCiDUI.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiDUI.SelectedText = "";
            this.txtCiDUI.SelectionLength = 0;
            this.txtCiDUI.SelectionStart = 0;
            this.txtCiDUI.ShortcutsEnabled = true;
            this.txtCiDUI.Size = new System.Drawing.Size(208, 29);
            this.txtCiDUI.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiDUI.TabIndex = 26;
            this.txtCiDUI.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiDUI.TextMarginBottom = 0;
            this.txtCiDUI.TextMarginLeft = 1;
            this.txtCiDUI.TextMarginTop = 1;
            this.txtCiDUI.TextPlaceholder = "DUI";
            this.txtCiDUI.UseSystemPasswordChar = false;
            this.txtCiDUI.WordWrap = true;
            // 
            // txtCiApellido
            // 
            this.txtCiApellido.AcceptsReturn = false;
            this.txtCiApellido.AcceptsTab = false;
            this.txtCiApellido.AnimationSpeed = 200;
            this.txtCiApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCiApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCiApellido.AutoSizeHeight = true;
            this.txtCiApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtCiApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCiApellido.BackgroundImage")));
            this.txtCiApellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCiApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCiApellido.BorderRadius = 20;
            this.txtCiApellido.BorderThickness = 1;
            this.txtCiApellido.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCiApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCiApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCiApellido.DefaultText = "";
            this.txtCiApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCiApellido.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.txtCiApellido.HideSelection = true;
            this.txtCiApellido.IconLeft = null;
            this.txtCiApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.IconPadding = 10;
            this.txtCiApellido.IconRight = null;
            this.txtCiApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCiApellido.Lines = new string[0];
            this.txtCiApellido.Location = new System.Drawing.Point(733, 4);
            this.txtCiApellido.Margin = new System.Windows.Forms.Padding(4);
            this.txtCiApellido.MaxLength = 32767;
            this.txtCiApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCiApellido.Modified = false;
            this.txtCiApellido.Multiline = false;
            this.txtCiApellido.Name = "txtCiApellido";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCiApellido.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCiApellido.OnIdleState = stateProperties24;
            this.txtCiApellido.Padding = new System.Windows.Forms.Padding(4);
            this.txtCiApellido.PasswordChar = '\0';
            this.txtCiApellido.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCiApellido.PlaceholderText = "Apellido";
            this.txtCiApellido.ReadOnly = false;
            this.txtCiApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCiApellido.SelectedText = "";
            this.txtCiApellido.SelectionLength = 0;
            this.txtCiApellido.SelectionStart = 0;
            this.txtCiApellido.ShortcutsEnabled = true;
            this.txtCiApellido.Size = new System.Drawing.Size(413, 29);
            this.txtCiApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCiApellido.TabIndex = 28;
            this.txtCiApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCiApellido.TextMarginBottom = 0;
            this.txtCiApellido.TextMarginLeft = 1;
            this.txtCiApellido.TextMarginTop = 1;
            this.txtCiApellido.TextPlaceholder = "Apellido";
            this.txtCiApellido.UseSystemPasswordChar = false;
            this.txtCiApellido.WordWrap = true;
            // 
            // tableLayoutPanel16
            // 
            this.tableLayoutPanel16.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(78)))), ((int)(((byte)(172)))));
            this.tableLayoutPanel16.ColumnCount = 7;
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.216438F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20.41935F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.021993F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25.26637F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.918864F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36.00417F));
            this.tableLayoutPanel16.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.152824F));
            this.tableLayoutPanel16.Controls.Add(this.label1, 1, 1);
            this.tableLayoutPanel16.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel16.Location = new System.Drawing.Point(4, 4);
            this.tableLayoutPanel16.Margin = new System.Windows.Forms.Padding(4);
            this.tableLayoutPanel16.Name = "tableLayoutPanel16";
            this.tableLayoutPanel16.RowCount = 3;
            this.tableLayoutPanel16.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.75F));
            this.tableLayoutPanel16.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 43.75F));
            this.tableLayoutPanel16.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 21.64948F));
            this.tableLayoutPanel16.Size = new System.Drawing.Size(1217, 98);
            this.tableLayoutPanel16.TabIndex = 17;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(67, 33);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(119, 43);
            this.label1.TabIndex = 0;
            this.label1.Text = "Visita";
            // 
            // ViewScheduleAppointment
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1371, 750);
            this.Controls.Add(this.tableLayoutPanel13);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "ViewScheduleAppointment";
            this.Text = "ViewScheduleAppointment";
            this.tableLayoutPanel13.ResumeLayout(false);
            this.tableLayoutPanel14.ResumeLayout(false);
            this.tableLayoutPanel14.PerformLayout();
            this.tableLayoutPanel12.ResumeLayout(false);
            this.tableLayoutPanel20.ResumeLayout(false);
            this.tableLayoutPanel19.ResumeLayout(false);
            this.tableLayoutPanel15.ResumeLayout(false);
            this.tableLayoutPanel17.ResumeLayout(false);
            this.tableLayoutPanel18.ResumeLayout(false);
            this.tableLayoutPanel16.ResumeLayout(false);
            this.tableLayoutPanel16.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.TableLayoutPanel tableLayoutPanel13;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel14;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel12;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel20;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnActualizar;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAgendar;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel19;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiObs;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel15;
        public Bunifu.UI.WinForms.BunifuDatePicker DTPfechacita;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel17;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiTel;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiCorreo;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel18;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiNombre;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiDUI;
        public Bunifu.UI.WinForms.BunifuTextBox txtCiApellido;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel16;
        private System.Windows.Forms.Label label1;
    }
}